### PR TITLE
ksize is not initialized before usage sometimes

### PR DESCRIPTION
**Pull request by ducha-aiki**

### CODE REVIEW

**Comment by edgarriba** [comment]
@ducha-aiki checked differences and seems quite the same. at least from visual perspective

before
image

after
image

**Comment by edgarriba** [comment]
@ducha-aiki is this fixed somewhere ?

**Comment by ducha-aiki** [comment]
yes, here https://github.com/kornia/kornia/pull/591

**Comment by edgarriba** [comment]
great. Closing in favour of #591

**Pull request closed without merging**
