### PR TITLE
[Feature] average quaternions

### LINKED ISSUE #2485: [Feature] implement average quaternions
## 🚀 Feature

Average quaternions

https://github.com/christophhagen/averaging-quaternions/blob/master/averageQuaternions.py

## Motivation

```python
def average_quaternions(quaternions: list[Quaternion] | Quaternion):
    ...
```

To discuss inputs
- list of single quaternions 
- batched Quaternion

## Additional context

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

### PR DESCRIPTION
**Pull request by Zekrom-7780**
#### Changes

- Added the `average-quaternion` function
- Don't know where to add it
- Ran `pre-commit` on my commits

Fixes #2485 

#### Type of change

- [x] 🔬 New feature (non-breaking change which adds functionality)
- [x] 📝 This change requires a documentation update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

#### Reviewers 

cc @edgarriba 

P.S. I'm not sure as to what exactly are we doing here, so I just tried whatever I understood.
Also could you help me on how to write unit-tests for this?

### CODE REVIEW

**Review by edgarriba — CHANGES_REQUESTED** [review]
besides the inline comments, this needs unit tests. Please, follow: https://github.com/kornia/kornia/blob/master/CONTRIBUTING.md

**Comment by Zekrom-7780** [comment]
@edgarriba please look at the changes made, if they seem correct, I'll move in making the unit-tests for this

Also, where should I make the unit-tests?

**Review by johnnv1 — COMMENTED** [review]
The tests should go here https://github.com/kornia/kornia/blob/master/test/geometry/test_quaternion.py

**Review by johnnv1 — CHANGES_REQUESTED** [review]
needs some tests

**Comment by johnnv1** [comment]
hey @Zekrom-7780, will you continue working on this?

**Comment by Zekrom-7780** [comment]
Hello @johnnv1 yes, but please gimme like 2 weeks, i'm in the process of moving in a new city, and like finding places to live and all.

**Comment by johnnv1** [comment]
as part of https://github.com/kornia/kornia/discussions/2719 plan, we have deleted the `master` in favor of `main`, if anyone has an interest in keep/restart working on this, let me know to help you.

**Pull request closed without merging**
