### PR TITLE
[Feat] implements histogram2d

### PR DESCRIPTION
**Pull request by connorlee77**
Add histogram and histogram2d (joint histogram) into kornia. Marginal and joint pdfs calculated using kernel density estimation to keep memory and time complexity costs down.

Created new branch as per @edgarriba's request

### CODE REVIEW

**Comment by connorlee77** [comment]
@edgarriba @ducha-aiki created the new PR from this: https://github.com/kornia/kornia/pull/509

**Comment by edgarriba** [comment]
@connorlee77 are the tests passing in local ??

**Comment by edgarriba** [comment]
@connorlee77 oh yeah. Finally, will merge now. Thanks so much !

**Comment by edgarriba** [comment]
I was wondering if you could do a short tutorial (colab might work) showing basically how to use this to visualize the histogram of an image, or more interesting of computed features. Leave it to you :)

**Comment by connorlee77** [comment]
@edgarriba will do in the next week!

**Comment by edgarriba** [comment]
@connorlee77 great! no rush :)

**Pull request merged**
