### PR TITLE
RandomSaltAndPepperNoise: Update algorithm to use indexing

### PR DESCRIPTION
**Pull request by vgilabert94**
#### Changes

Fixes # (issue)
Update algorithm using indexing instead of masking (add and multiply)

image

#### Type of change

- [x] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by vgilabert94** [comment]
About this comment: https://github.com/kornia/kornia/pull/2746#discussion_r1466107480
I'm not sure what the problem is. 
I have tested with keepdims=True and False and it works fine. When True the tensor returned is the same shape as the input.

**Comment by johnnv1** [comment]
can you provide the code snippet you use to benchmark it?

**Comment by vgilabert94** [comment]
> can you provide the code snippet you use to benchmark it?

https://colab.research.google.com/drive/1Kn3tncv8OuKS2NYBX3iDCI41O0JtQXo9?usp=sharing

**Comment by johnnv1** [comment]
can you update to benchmark using https://pytorch.org/tutorials/recipes/recipes/benchmark.html?

We have some examples with it at https://github.com/kornia/kornia-benchmark

**Comment by vgilabert94** [comment]
Results in same google colab: https://colab.research.google.com/drive/1Kn3tncv8OuKS2NYBX3iDCI41O0JtQXo9?usp=sharing

[------- RandomSaltAndPepperNoiseInd --------] INDEXING
                      |    cpu     |    cuda  
1 threads: -----------------------------------
      1-128-float32   |     923.6  |    1090.1
      1-256-float32   |    1876.8  |    1916.4
      1-512-float32   |    5526.4  |    6236.8
      1-1024-float32  |   32705.3  |   19179.2
      1-2048-float32  |   86819.9  |   77915.7
      3-128-float32   |    1592.3  |    1625.1
      3-256-float32   |    4296.0  |    4118.3
      3-512-float32   |   25607.6  |   14251.0
      3-1024-float32  |   64382.9  |   57882.6
      3-2048-float32  |  385795.5  |  318388.4
      5-128-float32   |    2605.5  |    2172.6
      5-256-float32   |    6995.3  |    6341.3
      5-512-float32   |   27763.1  |   37313.1
      5-1024-float32  |  109416.1  |   96997.0
      5-2048-float32  |  727704.7  |  615239.6
      1-128-float64   |     981.4  |    1069.0
      1-256-float64   |    1968.8  |    3016.7
      1-512-float64   |    9003.0  |    6988.5
      1-1024-float64  |   22457.5  |   19347.0
      1-2048-float64  |   93065.8  |  109904.0
      3-128-float64   |    1627.6  |    1641.7
      3-256-float64   |    8484.8  |    3960.6
      3-512-float64   |   16097.2  |   13964.7
      3-1024-float64  |   68900.3  |   81130.4
      3-2048-float64  |  400060.8  |  295590.5
      5-128-float64   |    2232.4  |    2242.0
      5-256-float64   |    6991.0  |    8076.4
      5-512-float64   |   26808.3  |   23044.9
      5-1024-float64  |  114107.9  |   96691.1
      5-2048-float64  |  745196.8  |  580635.3
Times are in microseconds (us).


[---------- RandomSaltAndPepperNoise ----------] MASKING
                      |     cpu     |     cuda  
1 threads: -------------------------------------
      1-128-float32   |      950.7  |     1165.1
      1-256-float32   |     1984.6  |     2318.1
      1-512-float32   |     6524.9  |     6396.5
      1-1024-float32  |    23955.1  |    24147.7
      1-2048-float32  |   108397.3  |   100509.2
      3-128-float32   |     1736.2  |     2941.2
      3-256-float32   |     4894.2  |     5006.2
      3-512-float32   |    18011.2  |    17792.4
      3-1024-float32  |    78122.5  |    89929.1
      3-2048-float32  |   609166.2  |   458319.9
      5-128-float32   |     3840.2  |     2607.7
      5-256-float32   |     7659.0  |     7891.7
      5-512-float32   |    31115.2  |    32844.0
      5-1024-float32  |   139080.6  |   126205.4
      5-2048-float32  |   982457.2  |   958448.1
      1-128-float64   |     1034.0  |     1297.8
      1-256-float64   |     2238.9  |     2634.9
      1-512-float64   |     7137.8  |     7206.1
      1-1024-float64  |    30766.2  |    28013.9
      1-2048-float64  |   179717.9  |   164003.7
      3-128-float64   |     1838.3  |     2075.8
      3-256-float64   |     9066.6  |     5594.9
      3-512-float64   |    21757.7  |    20722.1
      3-1024-float64  |    92723.7  |    89687.7
      3-2048-float64  |  1030341.2  |   593667.8
      5-128-float64   |     2651.4  |     2900.5
      5-256-float64   |     8570.7  |    12803.5
      5-512-float64   |    37268.8  |    35110.6
      5-1024-float64  |   364777.0  |   148942.3
      5-2048-float64  |  1385109.5  |  1155422.0
Times are in microseconds (us).

**Review by johnnv1 — APPROVED** [review]

**Pull request merged**
