### PR TITLE
tests_cpu.yml: Test on Python 3.10

### PR DESCRIPTION
**Pull request by cclauss**
#### Changes

Fixes # (issue)

#### Type of change

- [ ] 📚  Documentation Update
- [x] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by edgarriba** [comment]
@cclauss seems that both python 3.10 and torch 1.10 are causing some trouble here

**Comment by cclauss** [comment]
Resynced.

**Comment by edgarriba** [comment]
@cclauss seems that the working python 3.10 is only 3.10.0.0a0

**Comment by johnnv1** [comment]
closing in favor of #2025

**Pull request closed without merging**
