### PR TITLE
bugfix in KORNIA_CHECK_SHAPE

### PR DESCRIPTION
**Pull request by nitaifingerhut**
#### Changes
`KORNIA_CHECK_SHAPE` ignored non numeric dimensions, thus not validating the full required shape.
For example, the following lines passes though they should throw an error:
```
x = torch.rand(1, 1)
KORNIA_CHECK_SHAPE(x, ["B", "1", "H", "W"])
```

#### Type of change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)

#### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by edgarriba** [comment]
@cjpurackal seems that this fix discovers some issues in the new geometry stuff in liegroups and quaternion. We can co-work on that. 

@nitaifingerhut for context, the issue we have now is that quaternion and lie algebra support batched and non-batched tensors as a requirement for prod purposes. Which mean that the KORNIA_CHECK_SHAPE requires a bit of upgrades in the following direction:

```python
KORNIA_CHECK_SHAPE(quat, ("*", 4)
# (4,) == fail
# (1, 4) == ok
# (2, 1, 4) == ok
# (1, 3) == fail

KORNIA_CHECK_SHAPE(quat, ((None, "B"), 4)
# (4,) == ok
# (1, 4) == ok
# (2, 1, 4) == fail
# (1, 3) == fail
```

/cc discussed with @ducha-aiki  at some point

**Comment by nitaifingerhut** [comment]
@edgarriba yah I see that it's failing on what you mentioned...
so what do you want to do? since the current implementation is definitely a bug...

**Comment by edgarriba** [comment]
as a quick fix, lets temporary comment where it crashes in this PR ?

**Comment by nitaifingerhut** [comment]
@edgarriba as long as you want to improve this even further-
let's try to support "*" on both start and end

**Comment by nitaifingerhut** [comment]
> as a quick fix, lets temporary comment where it crashes in this PR ?

hmmm... not sure what's better. who can fix this?

**Comment by nitaifingerhut** [comment]
@edgarriba what's up with this one?

**Comment by edgarriba** [comment]
> @edgarriba what's up with this one?

comment the crashes in this pr with comment as temp fix

**Comment by nitaifingerhut** [comment]
> > @edgarriba what's up with this one?
> 
> comment the crashes in this pr with comment as temp fix

comment only the tests? or code itself?

**Comment by edgarriba** [comment]
code, sorry

**Pull request closed without merging**
