### PR TITLE
Fixes quaternion to angle axis

### PR DESCRIPTION
**Pull request by edgarriba**
### Description

Continuation of https://github.com/kornia/kornia/pull/926

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [ ] Docstrings/Documentation updated

### PR Implementer
This is a small checklist for the implementation details of this PR.

If there are any questions regarding code style or other conventions check out our 
[summary](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst).

- [ ] Did you discuss the functionality or any breaking changes before ?
- [ ] **Pass all tests**: did you test in local ? `make test`
- [ ] Unittests: did you add tests for your new functionality ?
- [ ] Documentations: did you build documentation ? `make build-docs`
- [ ] Implementation: is your code well commented and follow conventions ? `make lint`
- [ ] Docstrings & Typing: has your code documentation and typing ? `make mypy`
- [ ] Update notebooks & documentation if necessary

### KorniaTeam
<details>
  <summary>KorniaTeam workflow</summary>
  
  - [ ] Assign correct label
  - [ ] Assign PR to a reviewer
  - [ ] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if 
        not already in description)

</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>

  - [ ] Do all tests pass? (Unittests, Typing, Linting, Documentation, Environment)
  - [ ] Does the implementation follow `kornia` design conventions?
  - [ ] Is the documentation complete enough ?
  - [ ] Are the tests covering simple and corner cases ?
 
</details>

### CODE REVIEW

**Comment by edgarriba** [comment]
@amonszpart can you check this ? I had to remove the enums to make torchscript to work. It will be a bit to have strings but in any case we’ll deprecate soon , right ?

**Comment by amonszpart** [comment]
Ah, just saw this, double work it seems.
Can you please send me an e-mail next time, I don't seem to be able to configure GitHub to send me e-mails for your messages...:/

I'll take a look today.

**Comment by amonszpart** [comment]
> @amonszpart can you check this ? I had to remove the enums to make torchscript to work. It will be a bit weak to have strings but in any case we’ll deprecate soon , right ?

Hi Edgar, I merged this PR into https://github.com/kornia/kornia/pull/926, but kept the Enum.

Also, not a big fan of lists, e.g. when checking with `in`: `if a in ['b', 'c']:` is equivalent to `if a in ('b', 'c'):`, but tuples are immutable, so should be faster:
```python
import timeit; timeit.timeit("if 'a' in ['b', 'c']: pass"), timeit.timeit("if 'a' in ('b', 'c'): pass")
Out[16]: (0.07368296198546886, 0.05757608299609274)
import timeit; timeit.timeit("if 'a' in ['b', 'c']: pass"), timeit.timeit("if 'a' in ('b', 'c'): pass")
Out[17]: (0.08628459699684754, 0.044494008005131036)
import timeit; timeit.timeit("if 'a' in ['b', 'c']: pass"), timeit.timeit("if 'a' in ('b', 'c'): pass")
Out[18]: (0.060275846015429124, 0.041947985999286175)
import timeit; timeit.timeit("if 'a' in ['b', 'c']: pass"), timeit.timeit("if 'a' in ('b', 'c'): pass")
Out[19]: (0.062412736006081104, 0.04416344501078129)
import timeit; timeit.timeit("if 'a' in ['b', 'c']: pass"), timeit.timeit("if 'a' in ('b', 'c'): pass")
Out[20]: (0.06035618999158032, 0.0403876360214781)
```

Not always apparently :) :
```python
import timeit; timeit.timeit("if 'a' in ['b', 'c']: pass", number=int(1e8)), timeit.timeit("if 'a' in ('b', 'c'): pass", number=int(1e8))
Out[14]: (4.383447182975942, 4.810871836001752)
import timeit; timeit.timeit("if 'a' in ['b', 'c']: pass", number=int(1e8)), timeit.timeit("if 'a' in ('b', 'c'): pass", number=int(1e8))
Out[15]: (4.3647192000062205, 4.336871596024139)
```

Regardless, I think it's good practice to try to use tuples as much as possible , so you don't accidentally modify something you don't want to.

Let me know, if you prefer this PR to https://github.com/kornia/kornia/pull/926, and I'll make a pass on this.

Thanks,
Aron

**Comment by edgarriba** [comment]
ok, cool. Then let's continue in #926

**Comment by edgarriba** [comment]
wasn't aware about those timing for `list` vs `tuple` - thanks for reporting :)

**Pull request closed without merging**
