### PR TITLE
create notebooks for py examples

### PR DESCRIPTION
**Pull request by HassanAlsamahi**
I added the following examples in py files into notebooks to be more interactive and clear.
-color_adjust.py
-color_conversions.py
-filter_blurring.py
-filter_gaussian.py
-filter_edges.py
-warp_affine
-warp_perspective

### CODE REVIEW

**Comment by edgarriba** [comment]
@HassanAlsamahi thanks for the contribution. We might have to think about whether we want to have the notebooks in the main repo. Notebooks are quite heavy since contain images. /cc @ducha-aiki

**Comment by HassanAlsamahi** [comment]
yeah, okay, thanks for your clarification

**Comment by ducha-aiki** [comment]
@HassanAlsamahi Could you please PR against https://github.com/arraiyopensource/kornia-examples?  I think, we will put notebooks there.

Thing we like to use notebook-diff
https://forums.fast.ai/t/jupyter-notebook-enhancements-tips-and-tricks/17064/16?u=ducha-aiki

Also, to make notebooks much lighter we might consider to just clear outputs before commiting.

**Comment by edgarriba** [comment]
@ducha-aiki good idea

**Comment by edgarriba** [comment]
@HassanAlsamahi I think we can close this since now part of the examples are auto-generated providing its .ipynb version of it

**Comment by edgarriba** [comment]
we have moved the examples to https://github.com/kornia/kornia-examples

**Pull request closed without merging**
