### PR TITLE
[TEST][DO NOT MERGE] update to pytorch v1.5.0

### PR DESCRIPTION
**Pull request by edgarriba**
Pytorch v1.5.0 is out. This branch is to update to it.
Release notes: https://github.com/pytorch/pytorch/releases/tag/v1.5.0

### CODE REVIEW

**Comment by edgarriba** [comment]
@ducha-aiki I've tested in local and seen some error in orientation calculation. Maybe its worth updating those functions with new histogram stuff ?

**Comment by edgarriba** [comment]
@lferraz maybe it's a good time to update testing with new pytest approach you mentioned :)

**Comment by edgarriba** [comment]
I'm gonna focus on the GPU integration as well

**Comment by shijianjian** [comment]
One update for the transform part from torchvision-0.6:
- RandomPerspective,  added fill param. ---- (RGB pixel fill value for area outside the rotated image. If int, it is used for all channels respectively. Default value is 0.)

We cannot support this (so does the fill param in RandomRotation) since we only support padding_mode ('zeros' | 'border' | 'reflect') in our API.

**Comment by edgarriba** [comment]
@shijianjian I found also an incosistency between kornia 0.2.0 and 0.2.1 with the affine transform. basically the transform we return, is broken

**Comment by shijianjian** [comment]
> @shijianjian I found also an incosistency between kornia 0.2.0 and 0.2.1 with the affine transform. basically the transform we return, is broken

I think our current version should be fine since I also tested with TorchVision using the same suite of parameters. Also, it has been refactored by @ducha-aiki in #474.

**Comment by edgarriba** [comment]
@shijianjian @ducha-aiki tests are fixed. I included a small change to start supporting different dtypes during testing since it was one of the issues. We'll marge this after @shijianjian PR for decoupling functionals in the augmentation api.

**Comment by connorlee77** [comment]
@edgarriba  has the bugfix for the laforienter padding been fixed in version 0.3.1? still seem to be seeing it...

**Comment by edgarriba** [comment]
no test covering it ? /cc @ducha-aiki

**Pull request merged**
