### PR TITLE
Drop `scipy` from dev dependencies

### PR DESCRIPTION
**Pull request by johnnv1**
#### Changes

Fixes https://github.com/kornia/kornia/issues/2590 replaces #2625

#### Type of change

- [ ] 📚  Documentation Update
- [x] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Review by edgarriba — APPROVED** [review]

**Review by edgarriba — COMMENTED** [review]
need to add onnxruntime in dev dependencies file

**Comment by johnnv1** [comment]
> need to add onnxruntime in dev dependencies file

in fact onnxruntime gpu has already been added, but CI won't install it because it doesn't have a GPU apparently

**Comment by edgarriba** [comment]
There’s no cpu version ?

**Comment by johnnv1** [comment]
> There’s no cpu version ?

https://pypi.org/project/onnxruntime/

https://pypi.org/project/onnxruntime-gpu/

https://onnxruntime.ai/docs/get-started/with-python.html#install-onnx-runtime

**Pull request merged**
