### PR TITLE
Added gradio Image Stitching demo link

### PR DESCRIPTION
**Pull request by kadirnar**
#### Changes
- [X] Added Hugging Face demo.

Fixed https://github.com/kornia/kornia/issues/53#issue-401715507

#### Type of change

- [X] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by NimaBoscarino** [comment]
This is awesome! Could you also embed the demo into the docs? You'll need to:

1. Make a new file called something like `stitching_gradio.html` under here: https://github.com/kornia/kornia/tree/master/docs/source/gradio
2. Fill that file with the following:

```html
<script type="module" src="https://gradio.s3-us-west-2.amazonaws.com/3.1.7/gradio.js"></script>
<gradio-app space="kornia/Image-Stitching"></gradio-app>
```

3. Embed it in the `image_stitching.rst` file with this:

```
.. raw:: html
    :file: gradio/stitching_gradio.html
```

That should embed it like the one on this page: https://kornia.readthedocs.io/en/latest/enhance.html

**Review by edgarriba — APPROVED** [review]

**Comment by edgarriba** [comment]
@kadirnar @NimaBoscarino for some reason is not showing up the whole thing

https://kornia.readthedocs.io/en/latest/applications/image_stitching.html

**Comment by kadirnar** [comment]
Hello @edgarriba ,

What is wrong? I didn't understand. I will send a PR request for module "fit_line". Is there something missing in this PR?

**Comment by NimaBoscarino** [comment]
It's just a path issue in the way the file was embedded, i.e. `gradio/stitching_gradio.html` where it should be `../gradio/stitching_gradio.html`. I can fix it with a PR tomorrow where I'll adjust any other demos that aren't rendering properly.

**Comment by edgarriba** [comment]
great!

**Pull request merged**
