### PR TITLE
onnx export device mismatch fix

### LINKED ISSUE #2995: Failed to export onnx model when I use kornia.geometry.transform.imgwarp.warp_perspective in the model forward function
### Discussed in https://github.com/kornia/kornia/discussions/2992

<div type='discussions-op-text'>

<sup>Originally posted by **knavezl** August 23, 2024</sup>
my export model code is:
input_img = torch.randn(1 ,4, 3, 864, 1536).cuda() 
num_cameras = 4
num_classes = 3
resolution = [360 ,4 ,360]
Y, Z, X = resolution
encoder_name = 'res50'
model_params = torch.load(pt_path) 
state_dict = {}
for key in model_params["state_dict"].keys():
    state_dict_key = key.replace('model.' , '') 
    state_dict[state_dict_key] = model_params["state_dict"][key] 
model = MVDet(Y, Z, X, encoder_type = encoder_name, num_cameras = num_cameras, num_classes = num_classes)
model.load_state_dict(state_dict,strict=True)
model.cuda()  
torch.onnx.export(model, input_img  , onnx_path, verbose=False,opset_version=13)

The error is：
File "/home/user/BEV/TrackTacular/WorldTrack/models/mvdet.py", line 172, in forward
feat_mems_ = warp_perspective(feat_cams_, proj_mats, (self.Y, self.X), align_corners=False)
File "/home/user/anaconda3/envs/pytorch2.1/lib/python3.9/site-packages/kornia/geometry/transform/imgwarp.py", line 126, in warp_perspective
grid = transform_points(src_norm_trans_dst_norm[:, None, None], grid)
File "/home/user/anaconda3/envs/pytorch2.1/lib/python3.9/site-packages/kornia/geometry/linalg.py", line 191, in transform_points
trans_01 = torch.repeat_interleave(trans_01, repeats=points_1.shape[0] // trans_01.shape[0], dim=0)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)

Have you tried to transform the model and encountered the same problem? Do you have any solutions?
</div>

### PR DESCRIPTION
**Pull request by Isalia20**
#### Changes
This edit fixes the error we got in the issues listed below. However exporting of the model with this function is still not possible yet since onnx doesn't support exporting **aten::linalg_inv** function from torch. This fix is somewhat "forward looking", so when onnx supports this function in the future, we don't get the device mismatch error.
```
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::linalg_inv' to ONNX opset version 19 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
``` 

Example code you can use to run it:
```
import torch
import torch.nn as nn
from kornia.geometry.transform import warp_perspective

class DummyWarpModel(nn.Module):
    def __init__(self, input_channels: int = 3, output_channels: int = 3, height: int = 224, width: int = 224):
        super(DummyWarpModel, self).__init__()
        self.conv1 = nn.Conv2d(input_channels, 16, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv2d(16, output_channels, kernel_size=3, stride=1, padding=1)
        self.height = height
        self.width = width

    def forward(self, x: torch.Tensor):
        x = torch.relu(self.conv1(x))
        M = torch.eye(3, device=x.device).unsqueeze(0).repeat(x.size(0), 1, 1)
        x = warp_perspective(x, M, dsize=(self.height, self.width))
        x = self.conv2(x)
        return x

model = DummyWarpModel()
model.eval()
model.cuda()
input_tensor = torch.randn(2, 3, 224, 224).cuda()

onnx_filepath = "dummy_warp_model.onnx"
torch.onnx.export(
    model,
    (input_tensor),
    onnx_filepath,
    opset_version=19,
)
```

Fixes #2995 and #2992 (The errors mentioned in those issues, model still is not exportable to onnx due to the limitation mentioned above)

#### Type of change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Review by johnnv1 — APPROVED** [review]

**Comment by johnnv1** [comment]
@Isalia20 could you add a export to onnx test for it?

**Comment by Isalia20** [comment]
Yes will add it, either today(late here) or tomorrow. But as mentioned in the PR, onnx export doesn't work due to the operation not being supported. So should I make a test which expects that error?

**Comment by johnnv1** [comment]
> Yes will add it, either today(late here) or tomorrow. But as mentioned in the PR, onnx export doesn't work due to the operation not being supported. So should I make a test which expects that error?

ouch, i see -- my bad, so isn't necessary the test now, we can add it later

**Comment by Isalia20** [comment]
I think we can merge this, no?

**Review by edgarriba — APPROVED** [review]

**Comment by 56789KD** [comment]
Issue of comment

**Pull request merged**
