### PR TITLE
move kornia check api to kornia.core.check

### LINKED ISSUE #1958: Move check functions to `kornia.core.logger`
As discussed i'll move in a follow up PR under `kornia.core.logger` -- the plan is to embed those functions also in a custom `logging` application.

_Originally posted by @edgarriba in https://github.com/kornia/kornia/issues/1948#issuecomment-1288629730_

### PR DESCRIPTION
**Pull request by edgarriba**
#### Changes

resolves #1958 

TODO:

- [x] add test to functions

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by ducha-aiki** [comment]
LGTM, except I don't like the name logger. Logger to me is something unnecessary - thing, which logs things. 
However our "KORNIA_CHECK_*" functions are actually part of the flow and can interrupt is. 
`kornia.core.safeguards` maybe or `kornia.core.verify` ?

**Comment by edgarriba** [comment]
logger is placeholder because in future i want to add actual logging before raising exceptions

**Comment by johnnv1** [comment]
> LGTM, except I don't like the name logger. Logger to me is something unnecessary - thing, which logs things. However our "KORNIA_CHECK_*" functions are actually part of the flow and can interrupt is. `kornia.core.safeguards` maybe or `kornia.core.verify` ?

+1 for something like `kornia.core.verify` -- we can add after logging before the raises, but these functions seem more aligned to checks than logging

**Comment by lferraz** [comment]
I agree with the naming, it is not the best one.

However, since the functions are called `X_CHECK_Y()`, why not `check`?

**Comment by edgarriba** [comment]
@ducha-aiki @ducha-aiki please approve

**Review by ducha-aiki — APPROVED** [review]

**Pull request merged**
