### PR TITLE
bump version 0.7.2

### PR DESCRIPTION
**Pull request by edgarriba**
#### Changes

release corresponding to end of Q1: https://github.com/kornia/kornia/discussions/2720

**Pending to merge**
- [x] https://github.com/kornia/kornia/pull/2828
- [ ] ~~https://github.com/kornia/kornia/pull/2789~~

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Review by johnnv1 — APPROVED** [review]

**Comment by johnnv1** [comment]
GPU tests are fine on you side @edgarriba?

**Comment by cjpurackal** [comment]
GPU tests failing on my end as well

```
FAILED tests/augmentation/test_augmentation.py::TestRandomGaussianBlur::test_cardinality[cuda-float32-batch_shape1] - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
FAILED tests/augmentation/test_augmentation.py::TestRandomGaussianBlur::test_noncontiguous[cuda-float32] - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
FAILED tests/augmentation/test_augmentation.py::TestRandomGaussianBlur::test_module[cuda-float32] - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
FAILED tests/augmentation/test_augmentation.py::TestRandomGaussianBlur::test_module_kernel_int[cuda-float32] - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
FAILED tests/augmentation/test_augmentation.py::TestRandomGaussianBlur::test_module_sigma_tensor[cuda-float32] - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
FAILED tests/augmentation/test_augmentation.py::TestRandomClahe::test_smoke[cuda-float32] - AssertionError: The values for attribute 'device' do not match: cuda:0 != cpu.
FAILED tests/augmentation/test_augmentation.py::TestPlanckianJitter::test_planckian_jitter_blackbody[cuda-float32] - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
FAILED tests/augmentation/test_augmentation.py::TestPlanckianJitter::test_planckian_jitter_cied[cuda-float32] - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
FAILED tests/augmentation/test_augmentation.py::TestPlanckianJitter::test_planckian_jitter_batch[cuda-float32] - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
FAILED tests/augmentation/test_augmentation.py::TestPlanckianJitter::test_planckian_jitter_same_on_batch[cuda-float32] - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by ducha-aiki** [comment]
```
../../miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py:1519: in _call_impl
    return forward_call(*args, **kwargs)
kornia/augmentation/base.py:200: in forward
    in_tensor = self.transform_tensor(in_tensor)
kornia/augmentation/_2d/base.py:38: in transform_tensor
    _validate_input_dtype(input, accepted_dtypes=[float16, float32, float64])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

input = tensor([[0.7891, 0.1348, 0.2188, 0.8203, 0.6953],
        [0.7305, 0.2324, 0.9023, 0.3906, 0.6172],
        [0.5000, 0...8984, 0.4902, 0.7148],
        [0.6953, 0.3613, 0.4668, 0.8008, 0.2402]], device='cuda:0',
       dtype=torch.bfloat16)
accepted_dtypes = [torch.float16, torch.float32, torch.float64]

    def _validate_input_dtype(input: Tensor, accepted_dtypes: List[torch.dtype]) -> None:
        r"""Check if the dtype of the input tensor is in the range of accepted_dtypes
        Args:
            input: Tensor
            accepted_dtypes: List. e.g. [torch.float32, torch.float64]
        """
        if input.dtype not in accepted_dtypes:
>           raise TypeError(f"Expected input of {accepted_dtypes}. Got {input.dtype}")
E           TypeError: Expected input of [torch.float16, torch.float32, torch.float64]. Got torch.bfloat16
```

Same for me, failing because of type mismatch

**Comment by ducha-aiki** [comment]
Now only PlankianJitter, RandomCLAHE and some of the float 16 tests are failing. The most of tests are fine

```
`tests/augmentation/test_augmentation.py::TestPlanckianJitter::test_planckian_jitter_blackbody[cuda-float32] FAILED                                                                          [  3%]
tests/augmentation/test_augmentation.py::TestPlanckianJitter::test_planckian_jitter_cied[cuda-float32] FAILED                                                                               [  3%]
tests/augmentation/test_augmentation.py::TestPlanckianJitter::test_planckian_jitter_batch[cuda-float32] FAILED                                                                              [  3%]
tests/augmentation/test_augmentation.py::TestPlanckianJitter::test_planckian_jitter_same_on_batch[cuda-float32] FAILED  
```

**Pull request merged**
