### PR TITLE
enabling different samplers in ColorJitter

### PR DESCRIPTION
**Pull request by nitaifingerhut**
#### Changes

Fixes # (issue)

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by nitaifingerhut** [comment]
@edgarriba @shijianjian

**Review by edgarriba — COMMENTED** [review]
@nitaifingerhut the code LGTM. @shijianjian is it worth to enable that from the base augmentation class level ?

**Comment by nitaifingerhut** [comment]
you can't always allow it from base class since not all augmentations have samplers... and here as well (ColorJitter) it has 4 different samplers...

**Comment by nitaifingerhut** [comment]
also, not so sure why tests are failing
care to help? 10x

**Comment by shijianjian** [comment]
> you can't always allow it from base class since not all augmentations have samplers... and here as well (ColorJitter) it has 4 different samplers... 

I think you may try iterate through the _param_generator for all the distribution attribute. Then use set_attr to make a universal function.

**Comment by nitaifingerhut** [comment]
@shijianjian but what if I want a different samplers for different attributes? per say I want brightness with Uniform and hue with Normal? your suggestion makes all samplers the same.

**Comment by nitaifingerhut** [comment]
@shijianjian also, I can't figure out why my tests are failing... why are the all Objects are None?

**Pull request closed without merging**
