### PR TITLE
Fix Normalize with integer inputs

### PR DESCRIPTION
**Pull request by adamjstewart**
#### Changes

To reproduce the issue, run the following code:
```python
import torch
from kornia.augmentation import Normalize

norm = Normalize(mean=0, std=1)
x = torch.rand(1, 4, 3, 3)
out = norm(x)
```
You should see the following error message:
```
Traceback (most recent call last):
  File "/Users/Adam/Downloads/test.py", line 6, in <module>
    out = norm(x)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.10/site-packages/kornia/augmentation/base.py", line 186, in forward
    output = self.apply_func(in_tensor, params, flags)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.10/site-packages/kornia/augmentation/base.py", line 256, in apply_func
    output = self.apply_transform(in_tensor, params=params, flags=flags, transform=trans_matrix)
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.10/site-packages/kornia/augmentation/_2d/intensity/normalize.py", line 66, in apply_transform
    return normalize(input, flags["mean"], flags["std"])
  File "/Users/Adam/.spack/.spack-env/view/lib/python3.10/site-packages/kornia/enhance/normalize.py", line 105, in normalize
    if len(mean.shape) == 0 or mean.shape[0] == 1:
AttributeError: 'int' object has no attribute 'shape'
```
This PR fixes this issue.

Note that this issue wasn't caught by mypy since int is considered a subset of float for type hints, but not for `isinstance`. According to [PEP 484](https://peps.python.org/pep-0484/#the-numeric-tower):

> Rather than requiring that users write `import numbers` and then use `numbers.Float` etc., this PEP proposes a straightforward shortcut that is almost as effective: when an argument is annotated as having type `float`, an argument of type `int` is acceptable

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Review by shijianjian — APPROVED** [review]
Looks reasonable~

**Review by johnnv1 — COMMENTED** [review]
LGTM, can you update the `__init__` typing for `mean` and `std` parameters to explicitly have `int`?

**Comment by edgarriba** [comment]
@johnnv1 i unblocked here

**Comment by adamjstewart** [comment]
Note that in terms of type hints, `float | int` is identical to `float`, so the previous type hints are already correct.

**Comment by johnnv1** [comment]
> Note that in terms of type hints, `float | int` is identical to `float`, so the previous type hints are already correct.

yep, the idea is just to be clear for the user / better doc

**Pull request merged**
