### PR TITLE
Run nightly CI just with labeled PR

### PR DESCRIPTION
**Pull request by johnnv1**
The nightly job will run the tests if the PR have the label `nightly`

(also rename the nightly workflow to match the rest)

### CODE REVIEW

**Comment by edgarriba** [comment]
so how does it work, we need to create a git label for this ? maybe we should add/update development notes

**Comment by johnnv1** [comment]
> so how does it work, we need to create a git label for this ? maybe we should add/update development notes

if we add a `nightly` label to the PR, the nightly job will run -- i can't create a label, can you do this? 😅

**Comment by edgarriba** [comment]
why there's a skipped test ?

**Comment by johnnv1** [comment]
> why there's a skipped test ?

The idea here is to not always run the nightly tests, so when the PR don't have the `nightly` label they will be skipped -- as you can see [in this test PR](https://github.com/johnnv1/kornia/pull/5) that tests run when the label (`nightly`) was added to PR

we can discuss a better way to trigger/run this case

**Comment by edgarriba** [comment]
i see, we can adopt by labeling but also if want to manually trigger via github actions tab

**Review by edgarriba — APPROVED** [review]

**Pull request merged**
