### PR TITLE
Add a "Contributing to Documentation" section to contribution g…

### PR DESCRIPTION
**Pull request by lappemic**
#### Changes
This PR adds a "Contributing to Documentation" section to the `CONTRIBUTING.md` file to welcome contributors to also improve the documentation. This should 
- encourage people to add improvements if they do not find what they are looking to and 
- add low entry barriers for first time contributors (potential `good first issue` in docs)

In summary this should help the adoption of kornia!

Addresses: #2957 

#### Type of change
- [x] 📚  Documentation Update

### CODE REVIEW

**Review by johnnv1 — APPROVED** [review]
Thank you for this patch

**Comment by lappemic** [comment]
Are we ready to merge or does this pr still need some changes @johnnv1?

**Comment by johnnv1** [comment]
> Are we ready to merge or does this pr still need some changes @johnnv1?

Yes, it's ready, but since the CI is falling (unrelated with this patch) I can't force the merge

**Comment by lappemic** [comment]
So, how to proceed then?

**Pull request merged**
