### PR TITLE
fix device and dtype in draw poly tests

### PR DESCRIPTION
**Pull request by edgarriba**
#### Changes

Fixes issue with cuda tests introduced in https://github.com/kornia/kornia/pull/1636

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by Parskatt** [comment]
@edgarriba oops, my bad. Changes looks good. There are some additional issues which I mentioned in #1641 regarding which coordinate systems are assumed.

**Comment by Parskatt** [comment]
@edgarriba Sorry to be a bother, but I also changed the naming to polygon**s**, which probably was stupid. I guess just removing all those s should be fine.

**Comment by edgarriba** [comment]
> @edgarriba Sorry to be a bother, but I also changed the naming to polygon**s**, which probably was stupid. I guess just removing all those s should be fine.

what it should be ? (and where) I can make the change if you point me in the right place

**Comment by Parskatt** [comment]
@edgarriba the function is literally named `draw_convex_polygons` not `draw_convex_polygon` as indicated in the release. To change it would mean just removing all the "s" in the source code.

**Pull request merged**
