### PR TITLE
fix cross_product_matrix batch dimensionality

### PR DESCRIPTION
**Pull request by nitaifingerhut**
#### Changes
`kornia.geometry.epipolar.numeric`

Fixes https://github.com/kornia/kornia/issues/1527

#### Type of change
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by edgarriba — COMMENTED** [review]
Could you add a test for this new behaviour?
https://github.com/kornia/kornia/blob/master/test/geometry/epipolar/test_numeric.py#L17

**Comment by nitaifingerhut** [comment]
@edgarriba added tests per your request

**Review by edgarriba — APPROVED** [review]
LGTM. We merge once we have green lights

**Comment by nitaifingerhut** [comment]
@ducha-aiki @shijianjian @lferraz can you please review so we can merge ?

**Pull request merged**
