### PR TITLE
added homography error metrics, and improved find_homography_iter

### PR DESCRIPTION
**Pull request by ducha-aiki**
### Description

Adds homography metrics, similar to how we have epipolar distance errors.
Also changes find_homography_dlt_iter to work on 2-way error (better) and makes tests. to generate more physically plausible homographies.
### Status
**Ready/Work in progress/Hold**

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or new feature that would cause existing functionality to change)
- [x] New tests added to cover the changes
- [x] Docstrings/Documentation updated

### PR Implementer
This is a small checklist for the implementation details of this PR.

If there are any questions regarding code style or other conventions check out our
[summary](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst).

- [ ] Did you discuss the functionality or any breaking changes before ?
- [ ] **Pass all tests**: did you test in local ? `make test`
- [x] Unittests: did you add tests for your new functionality ?
- [ ] Documentations: did you build documentation ? `make build-docs`
- [x] Implementation: is your code well commented and follow conventions ? `make lint`
- [x] Docstrings & Typing: has your code documentation and typing ? `make mypy`
- [ ] Update notebooks & documentation if necessary

### KorniaTeam
<details>
  <summary>KorniaTeam workflow</summary>

  - [ ] Assign correct label
  - [ ] Assign PR to a reviewer
  - [ ] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if
        not already in description)

</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>

  - [ ] Do all tests pass? (Unittests, Typing, Linting, Documentation, Environment)
  - [ ] Does the implementation follow `kornia` design conventions?
  - [ ] Is the documentation complete enough ?
  - [ ] Are the tests covering simple and corner cases ?

</details>

### CODE REVIEW

**Review by edgarriba — COMMENTED** [review]
Add to docs

**Comment by ducha-aiki** [comment]
> Add to docs

homography module add all members automtically:
https://github.com/kornia/kornia/blob/master/docs/source/geometry.homography.rst

**Comment by edgarriba** [comment]
great!

**Comment by edgarriba** [comment]
@ducha-aiki should we adopt across the library ?

**Comment by ducha-aiki** [comment]
Good idea, just need to figure out how to be with auxilary functions we don't export.

**Comment by edgarriba** [comment]
also thinking that in some modules we split by sections, like in `kornia.geometry.transform`

**Pull request merged**
