### PR TITLE
[DOC] Updated docstring for augmentation module

### PR DESCRIPTION
**Pull request by shijianjian**
### Description
A few sentences describing the changes proposed in this pull request.

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [x] Docstrings/Documentation updated

### PR Implementer
This is a small checklist for the implementation details of this PR.

If there are any questions regarding code style or other conventions check out our 
[summary](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst).

- [ ] Did you discuss the functionality or any breaking changes before ?
- [ ] **Pass all tests**: did you test in local ? `make test`
- [ ] Unittests: did you add tests for your new functionality ?
- [ ] Documentations: did you build documentation ? `make build-docs`
- [ ] Implementation: is your code well commented and follow conventions ? `make lint`
- [ ] Docstrings & Typing: has your code documentation and typing ? `make mypy`
- [ ] Update notebooks & documentation if necessary

### KorniaTeam
<details>
  <summary>KorniaTeam workflow</summary>
  
  - [ ] Assign correct label
  - [ ] Assign PR to a reviewer
  - [ ] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if 
        not already in description)

</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>

  - [ ] Do all tests pass? (Unittests, Typing, Linting, Documentation, Environment)
  - [ ] Does the implementation follow `kornia` design conventions?
  - [ ] Is the documentation complete enough ?
  - [ ] Are the tests covering simple and corner cases ?
 
</details>

### CODE REVIEW

**Comment by edgarriba** [comment]
@shijianjian could we try here doctest and docstring checker ? maybe in a separated PR

**Comment by shijianjian** [comment]
> @shijianjian could we try here doctest and docstring checker ? maybe in a separated PR

I think we can add it in. What test shall we include here? Are we moving everything apart from grad_check?

**Comment by edgarriba** [comment]
@shijianjian I would test docstyle just from public methods (I think this can be parametrized) and same for doctest

**Comment by shijianjian** [comment]
I have made ```pytest --doctest-modules kornia/augmentation``` worked. The only thing I dislike is to have a ```rng = torch.manual_seed(0)``` in front. Is there any way to set a testbed or anything like "before" operator? It would be best if we can have a global setting to make a default seed value.

**Comment by edgarriba** [comment]
@shijianjian I though we were able to pass the seed to the operator

**Pull request merged**
