### PR TITLE
disable accelerate for macos and pytorch 1.10.2

### PR DESCRIPTION
**Pull request by edgarriba**
#### Changes

Fixes # (issue)

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by edgarriba** [comment]
@sgugger @muellerzr is this a known issue ?

**Comment by muellerzr** [comment]
Torch 1.10.2 is supported, but we're working on Mac support very soon https://github.com/huggingface/accelerate/issues/453

**Comment by edgarriba** [comment]
Ok, is weird that in the ci currently we get accelerate failing to import (not to mention install) in macos and pt 1.12.0
See: https://github.com/kornia/kornia/actions/runs/2758324827

**Comment by muellerzr** [comment]
In the logs I see that Accelerate was indeed installed via pypi, but not found. We'll see if we notice something similar as we work towards Mac support

**Comment by edgarriba** [comment]
@muellerzr looking again into this. I isolated a bit the setup and for some reason there's a mismatch with torch.distribute

```bash
kornia/x/trainer.py:4: in <module>
    import accelerate
/usr/local/miniconda/envs/test/lib/python3.7/site-packages/accelerate/__init__.py:7: in <module>
    from .accelerator import Accelerator
/usr/local/miniconda/envs/test/lib/python3.7/site-packages/accelerate/accelerator.py:26: in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
/usr/local/miniconda/envs/test/lib/python3.7/site-packages/accelerate/checkpointing.py:24: in <module>
    from .utils import (
/usr/local/miniconda/envs/test/lib/python3.7/site-packages/accelerate/utils/__init__.py:55: in <module>
    from .operations import (
/usr/local/miniconda/envs/test/lib/python3.7/site-packages/accelerate/utils/operations.py:24: in <module>
    from torch.distributed import ReduceOp
E   ImportError: cannot import name 'ReduceOp' from 'torch.distributed' (/usr/local/miniconda/envs/test/lib/python3.7/site-packages/torch/distributed/__init__.py)
```
https://github.com/kornia/kornia/runs/7712846310?check_suite_focus=true

**Pull request merged**
