### PR TITLE
Change GaussianBlur to RandomGaussianBlur 

### PR DESCRIPTION
**Pull request by eugene87222**
### Description
Pull request for issue #1115

### Status
**Ready**

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [ ] Docstrings/Documentation updated

### PR Implementer
This is a small checklist for the implementation details of this PR.

If there are any questions regarding code style or other conventions check out our
[summary](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst).

- [ ] Did you discuss the functionality or any breaking changes before ?
- [ ] **Pass all tests**: did you test in local ? `make test`
- [ ] Unittests: did you add tests for your new functionality ?
- [ ] Documentations: did you build documentation ? `make build-docs`
- [ ] Implementation: is your code well commented and follow conventions ? `make lint`
- [ ] Docstrings & Typing: has your code documentation and typing ? `make mypy`
- [ ] Update notebooks & documentation if necessary

### KorniaTeam
<details>
  <summary>KorniaTeam workflow</summary>

  - [ ] Assign correct label
  - [ ] Assign PR to a reviewer
  - [ ] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if
        not already in description)

</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>

  - [ ] Do all tests pass? (Unittests, Typing, Linting, Documentation, Environment)
  - [ ] Does the implementation follow `kornia` design conventions?
  - [ ] Is the documentation complete enough ?
  - [ ] Are the tests covering simple and corner cases ?

</details>

### CODE REVIEW

**Review by shijianjian — COMMENTED** [review]
@edgarriba how can we prevent the pre-commit changes? A bit annoying to be honest. 

Those irrelevant parts shall be removed.

**Comment by eugene87222** [comment]
@shijianjian should I also change other occurences of `GaussianBlur` to `RandomGaussianBlur`?
I use searching bar in GitHub and notice that these three files use `GaussianBlur` as well.
- docs/source/augmentation.module.rst
- test/augmentation/test_augmentation.py
- kornia/augmentation/augmentation.py

**Comment by shijianjian** [comment]
> @shijianjian should I also change other occurences of `GaussianBlur` to `RandomGaussianBlur`?
> 
> I use searching bar in GitHub and notice that these three files use `GaussianBlur` as well.
> 
> - docs/source/augmentation.module.rst
> 
> - test/augmentation/test_augmentation.py
> 
> - kornia/augmentation/augmentation.py

Yes. Please do so.

**Review by edgarriba — APPROVED** [review]
LGTM. Please, rebase from master since the issues with numpy have been fixed there.

**Comment by eugene87222** [comment]
> 
> 
> LGTM. Please, rebase from master since the issues with numpy have been fixed there.

Sorry, may i ask how to do so 😭

**Comment by shijianjian** [comment]
> Sorry, may i ask how to do so 😭 

~~~
git pull --rebase upstream master
~~~

If your set Kornia main repo as upstream.

**Comment by eugene87222** [comment]
Is that correct?

**Comment by shijianjian** [comment]
I think you did a fast-forward merge than rebase. You should not have changed the GitHub workflow.

**Comment by eugene87222** [comment]
> 
> 
> I think you did a fast-forward merge than rebase. You should not have changed the GitHub workflow.

I have no idea how to redo now :(
I can show you the log tree on my computer.

**Comment by shijianjian** [comment]
> > 
> 
> > 
> 
> > I think you did a fast-forward merge than rebase. You should not have changed the GitHub workflow.
> 
> 
> 
> I have no idea how to redo now :(
> 
> I can show you the log tree on my computer.

You can try rebase correctly, then push with --force.

**Comment by eugene87222** [comment]
I just reset to the commit  to where I change all the occurances to `RandomGaussianBlur`, and execute `git pull --rebase kornia master`, then push to branch `issue-1115`.

**Comment by shijianjian** [comment]
Please check https://deepsource.io/gh/kornia/kornia/run/5b1e661e-6bdc-4068-b211-355a3a422b69/python/PYL-E0603.

You did not remove GaussianBlur in line 49.

**Review by shijianjian — APPROVED** [review]

**Comment by eugene87222** [comment]
I notice that I did not have GPG key on my computer and I just generate one now.
Should I sign those commits and push them again?

**Comment by shijianjian** [comment]
> I notice that I did not have GPG key on my computer and I just generate one now.
> 
> Should I sign those commits and push them again?

It's better to do so. You may sign all your commits and force push again.

**Pull request merged**
