### PR TITLE
[Feat] Enable variable side resizing in kornia.resize

### LINKED ISSUE #627: Make the resize anchor variable if size is int
## 🚀 Feature

Make the resize anchor variable if size is `int`.

## Motivation

Right now `kornia.resize` assumes that the shorter edge of the image should be resized to `size` if its an `int`. That can be cumbersome if the user wants for example an image that is not larger than x or wants a specific edge to be this size.

## Pitch

I propose we add an `edge` kwargs which can be one of `"short"` (default), `"long"`, `"vert"`, and `"horz"`. Based on this we calculate the `size`. It should have no effect if `size` is a `tuple` of `int`s.

### PR DESCRIPTION
**Pull request by pmeier**
Closes #627

### CODE REVIEW

**Review by ducha-aiki — CHANGES_REQUESTED** [review]
I really like the PR, but really don't like name "edge" here. First thing, what I thought about, when opened PR, was edge from edge detection, and I think it is a common association. 
Rename to, maybe, "side"?

**Comment by edgarriba** [comment]
@ducha-aiki good point!

**Comment by pmeier** [comment]
@ducha-aiki Rename is done.

**Review by ducha-aiki — APPROVED** [review]

**Comment by ducha-aiki** [comment]
Thanks. LGTM

**Pull request merged**
