### PR TITLE
Rename variables shadowing build-in input function

### LINKED ISSUE #1276: [Code health] Remove Re-definition found for builtin function
## 🚀 Feature

As reported by deepsource in [here](https://deepsource.io/gh/kornia/kornia/issue/PYL-W0622/occurrences?page=1) we abuse from using built-in `input` function in our functionality.

## Motivation

We target to have a clean and healthy source code free of risk.

## Pitch

Replace variable names whether it makes sense e.g. for image based functionality `input` -> `image` ; in losses `input` -> `pred` (or similar)
______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

### PR DESCRIPTION
**Pull request by alorthius**
#### Changes
Renamed variables `input` to `input_tensor` and `input_` in a few files and folders as stated in issue #1276. Renamed a bunch of them

#### Type of change

- [x] 🧪 Tests Cases

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by johnnv1 — APPROVED** [review]
LGTM, I personally think `input_tensor` is kinda big, but I don't have a better name in mind -- @edgarriba @ducha-aiki do you think we should be careful when renaming parameters because of backward compatibility?

**Comment by edgarriba** [comment]
>  I personally think input_tensor is ...

what about `pred` for losses, `image` for image based operators?

**Comment by johnnv1** [comment]
> what about `pred` for losses, `image` for image based operators?

works for me, @alorthius can you update it?

**Comment by alorthius** [comment]
updated it @johnnv1 @edgarriba

**Review by edgarriba — APPROVED** [review]

**Review by johnnv1 — APPROVED** [review]

**Pull request merged**
