### PR TITLE
use autopep8 instead of yapf for performance

### PR DESCRIPTION
**Pull request by asottile**
this is *one* approach to getting pre-commit to complete in a reasonable amount of time -- `yapf` seems to be terribly slow on this repository (it may be terribly slow in general, I don't have too much experience with it).

generally there's two other alternatives to `yapf`:
- `autopep8`
   - pros: much faster
   - cons: doesn't reformat as many things as `yapf` (for instance, you probably also want [add-trailing-comma](https://github.com/asottile/add-trailing-comma) to accompany it)
- `black`
    - pros: also much faster
    - cons: very opinionated and not configurable (it reformats a lot of your existing code to a quite different style)

generally I would suggest `black` for those looking for a one-pony formatter -- though this PR uses `autopep8` -- let me know if you'd like me to try `black` on this repository instead

___

### Description
A few sentences describing the changes proposed in this pull request.

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [x] Docstrings/Documentation updated

### PR Implementer
This is a small checklist for the implementation details of this PR.

If there are any questions regarding code style or other conventions check out our
[summary](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst).

- [ ] Did you discuss the functionality or any breaking changes before ?
- [ ] **Pass all tests**: did you test in local ? `make test`
- [ ] Unittests: did you add tests for your new functionality ?
- [ ] Documentations: did you build documentation ? `make build-docs`
- [ ] Implementation: is your code well commented and follow conventions ? `make lint`
- [ ] Docstrings & Typing: has your code documentation and typing ? `make mypy`
- [ ] Update notebooks & documentation if necessary

### KorniaTeam
<details>
  <summary>KorniaTeam workflow</summary>

  - [ ] Assign correct label
  - [ ] Assign PR to a reviewer
  - [ ] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if
        not already in description)

</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>

  - [ ] Do all tests pass? (Unittests, Typing, Linting, Documentation, Environment)
  - [ ] Does the implementation follow `kornia` design conventions?
  - [ ] Is the documentation complete enough ?
  - [ ] Are the tests covering simple and corner cases ?

</details>

### CODE REVIEW

**Comment by asottile** [comment]
cool, this run is well under the time limit at ~29s

**Comment by edgarriba** [comment]
@Borda I guess then we should stick to autopep

**Comment by asottile** [comment]
let me open up the `black` PR so you can compare 👍

**Comment by Borda** [comment]
> `yapf` seems to be terribly slow on this repository

Not sure what you mean by slow, depends if you run it on diff or full repo, talking about black, it is just personal preference, there is no specific reason why it shall be better... Moreover I don't think it much faster, can you give some benchmark?

**Comment by edgarriba** [comment]
@asottile let us do quick internal discussion about this. Thanks so much for this quick responses :sunglasses:

**Comment by asottile** [comment]
> 
> 
> > `yapf` seems to be terribly slow on this repository
> 
> Not sure what you mean by slow, depends if you run it on diff or full repo, talking about black, it is just personal preference, there is no specific reason why it shall be better... Moreover I don't think it much faster, can you give some benchmark?

yep!  here's a small demo showing black being 20x faster than yapf on a single file in your codebase:

```bash
f=test/augmentation/test_augmentation.py

yapf -i "$f"  # stabilize formatting
time yapf -i "$f"

black --skip-string-normalization --line-length=120 "$f"  # stabilize formatting
rm -rf ~/.cache/black  # skip black's cache
time black --skip-string-normalization --line-length=120 "$f"
```

```console
$ bash -x t.sh
+ f=test/augmentation/test_augmentation.py
+ yapf -i test/augmentation/test_augmentation.py
+ yapf -i test/augmentation/test_augmentation.py

real	1m4.935s
user	1m4.697s
sys	0m0.173s
+ black --skip-string-normalization --line-length=120 test/augmentation/test_augmentation.py
reformatted test/augmentation/test_augmentation.py
All done! ✨ 🍰 ✨
1 file reformatted.
+ rm -rf /home/asottile/.cache/black
+ black --skip-string-normalization --line-length=120 test/augmentation/test_augmentation.py
All done! ✨ 🍰 ✨
1 file left unchanged.

real	0m3.560s
user	0m3.518s
sys	0m0.040s
```

**Comment by Borda** [comment]
> yep! here's a small demo showing black being 20x faster than yapf on a single file in your codebase:

well, single file is not very fair :D but I see your point... :]

**Comment by asottile** [comment]
> > yep! here's a small demo showing black being 20x faster than yapf on a single file in your codebase:
> 
> well, a single file is not very fair :D but I see your point... :]
> Also to be clear autopep8 is cool, but it not fomatter, just fixing PEP8 issue (correct me if I am wrong)

heh, well black can format the entire codebase more than five times in the time it takes yapf to format that one file (there are other files which take similar amounts of time)

**Comment by edgarriba** [comment]
closing in favor of https://github.com/kornia/kornia/pull/1052

**Pull request closed without merging**
