### PR TITLE
Replace miniconda for `setup-python@v4` on env setup CI

### PR DESCRIPTION
**Pull request by johnnv1**
This patch replaces the `setup-miniconda` with the default `setup-python`. ~The idea is to use the caching tool already configured on it to try to speed up the CI.~

### CODE REVIEW

**Review by edgarriba — APPROVED** [review]
I’d also revisit too the setup dev script

**Comment by johnnv1** [comment]
> I’d also revisit too the setup dev script

I don't have the habit of using it, but I think is valid to use the conda there, since normally GPU is easy to set up with conda

**Comment by edgarriba** [comment]
@johnnv1 what is your workflow then ?

**Comment by johnnv1** [comment]
> @johnnv1 what is your workflow then ?

Well, I have a conda env in place with the Pytorch configured, then I always copy this env and use from it

I had this conda env in place most to make sure pytorch is configured correctly with my GPU -- and I am not a big fan of conda too, just use it because Pypi wheels don't have a binary for the 3060 (at least for old versions) + conda takes care of cudatoolkit inside of the env instead of mess up with the global one

Example of what I do when playing with kornia: 

```shell
$ cd /tmp/
$ git clone ...
$ cd kornia
$ conda create --clone dl-pt-base -p ./venv/ --copy
$ conda activate venv/
$ pip install .[dev]

```

**Comment by johnnv1** [comment]
The problem with caching pytorch is it is too big, and probably not worth it xD

image

**Comment by johnnv1** [comment]
Even without caching it seems that Pypi is faster than the conda option. This pypi action set up the requirements in 40~50 seconds and the conda takes 1.5~2 min. So, I will merge it for now, and we can monitor how it will perform  😄

**Pull request merged**
