### PR TITLE
Refactor SOLD2 and WunschLineMatcher Dict Config to Dataclasses

### PR DESCRIPTION
**Pull request by lappemic**
This PR updates the SOLD2 and WunschLineMatcher configurations to use dataclasses, aligning with issue #2093. It builds on the changes from PR #2899, which consolidated SOLD2 dataclasses into kornia.feature.sold2.structures.

### CODE REVIEW

**Comment by lappemic** [comment]
Hey @edgarriba, this is still an addition the the Dict to Dataclass refactoring. As far as i see, the ci error is the same as before in #2899.

Cc @johnnv1

**Review by johnnv1 — APPROVED** [review]

**Review by edgarriba — APPROVED** [review]

**Comment by johnnv1** [comment]
hey, @lappemic the failing tutorial is related to sold2, could you check it?

**Comment by lappemic** [comment]
@johnnv1 found the error in the tutorials (was related to wrongliy configured `LineMatcherCfg`). The one failing now is the same as always, right?

**Comment by johnnv1** [comment]
> @johnnv1 found the error in the tutorials (was related to wrongliy configured `LineMatcherCfg`). The one failing now is the same as always, right?

yeah, it's fine, tks!

**Pull request merged**
