### PR TITLE
Add an interactive demo to the kornia.enhance docs

### PR DESCRIPTION
**Pull request by NimaBoscarino**
#### Changes
I thought that having interactive demos in the docs would be a nice way for users to quickly get to tinker with the methods without having to spin up a Colab notebook or a local environment. This PR includes an example demo for some of the `kornia.enhance` methods, embedded at the bottom of the doc.

The demo is built with Gradio and hosted on Hugging Face Spaces. If this is interesting, making more of these should be pretty simple!

#### Type of change
- [x] 📚  Documentation Update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas (N/A)
- [ ] I have made corresponding changes to the documentation (N/A)
- [x] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change? (N/A)

### CODE REVIEW

**Review by edgarriba — APPROVED** [review]
@NimaBoscarino thanks so much for the contribution! This looks like a good idea to me. Some people from your org pointed to us even to create a HF/kornia sort of org. Maybe will make sense to go in this direction ? /cc @ducha-aiki @osanseviero

Some suggestions about the app: does it support Gradio to show in grid ? one of the strongest points of kornia is that can be run in batch. Also for image loading, I'd suggest to use our new kornia.io api https://kornia.readthedocs.io/en/latest/io.html based on Rust. We are planning to improve that, specially to target robotics/safe applications. I can contribute on that.

**UPDATE**: just created the kornia org https://huggingface.co/kornia

**Comment by osanseviero** [comment]
Maybe we could move the space to a `kornia` organization on Hugging Face and add you there as well if you want to make any changes. I think it would be nice specially if we want to add more demos. WDYT?

cc @julien-c

**Comment by NimaBoscarino** [comment]
@edgarriba Awesome, glad you like it! And thanks for the PR to the Space 🥳 I think I can only transfer the repo over if I'm part of the org first, so I sent a request to join the Kornia org.

> does it support Gradio to show in grid ?

Totally! I'm fairly sure that I can modify it to do batches of images pretty easily. I'll give that a try tomorrow! Afterwards, I can dig through the docs to find more candidates for demos, but definitely let me know if you have any in mind.

**Comment by edgarriba** [comment]
awesome ! lets maybe setup a call or something

**Comment by NimaBoscarino** [comment]
Sounds great! I'll message you over on the Hugging Face Slack 😄

**Comment by julien-c** [comment]
This is awesome and super exciting!! Looking forward to more collaboration!

**Pull request merged**
