### PR TITLE
fix the docs of quaternion_to_angle_axis()

### PR DESCRIPTION
**Pull request by sundw2014**
### Description
Documentation for quaternion_to_angle_axis() was wrong. ```quaternion``` used in quaternion_to_angle_axis() is actually assumed to be in the format of ```[w, x, y, z]```. I fixed the docs in this pull request.

Changing the API of quaternion_to_angle_axis() would be a better way to make it compatible with other quaternion-related functions. However, I'm not sure if doing this will cause some existing programs based on kornia to crash.

### Status
**Ready**

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [ ] Docstrings/Documentation updated

### PR Implementer
This is a small checklist for the implementation details of this PR.

If there are any questions regarding code style or other conventions check out our 
[summary](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst).

- [ ] Did you discuss the functionality or any breaking changes before ?
- [ ] **Pass all tests**: did you test in local ? `make test`
- [ ] Unittests: did you add tests for your new functionality ?
- [ ] Documentations: did you build documentation ? `make build-docs`
- [ ] Implementation: is your code well commented and follow conventions ? `make lint`
- [ ] Docstrings & Typing: has your code documentation and typing ? `make mypy`
- [ ] Update notebooks & documentation if necessary

### KorniaTeam
<details>
  <summary>KorniaTeam workflow</summary>
  
  - [ ] Assign correct label
  - [ ] Assign PR to a reviewer
  - [ ] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if 
        not already in description)

</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>

  - [ ] Do all tests pass? (Unittests, Typing, Linting, Documentation, Environment)
  - [ ] Does the implementation follow `kornia` design conventions?
  - [ ] Is the documentation complete enough ?
  - [ ] Are the tests covering simple and corner cases ?
 
</details>

### CODE REVIEW

**Comment by edgarriba** [comment]
@sundw2014 we can definitely discuss this API since is somehow broken and few functions seems to be not consistent at all. What are your suggestions here ? /cc @krrish94

**Comment by sundw2014** [comment]
Hi @edgarriba, sorry for the late response. By changing API, I meant something like this #636.

**Comment by hiyyg** [comment]
I think (w,x,y,z) format is more consistent with other libraries like pyquaternion and transforms3d. @edgarriba @sundw2014

**Comment by edgarriba** [comment]
@hiyyg @sundw2014 then let's go pyquaternion or transforms3d representation. If you guys can give a hand on that, would be awesome

**Comment by edgarriba** [comment]
closing in favor of https://github.com/kornia/kornia/pull/926

**Pull request closed without merging**
