### PR TITLE
Added Hugging Face edge detection demo link

### LINKED ISSUE #1878: Morphological operators tutorial
## 📚 Documentation

https://github.com/kornia/kornia/issues/53
Hugging space demo and embedded app

### PR DESCRIPTION
**Pull request by ramon-rd**
#### Changes

Fixes #1878 

#### Type of change

- [x] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Review by edgarriba — APPROVED** [review]

**Comment by edgarriba** [comment]
@ramon-rd just realizing that this needs to be added in the docs rst files so that can show up online
/cc @NimaBoscarino

**Comment by ramon-rd** [comment]
Ok, just to be sure..  the morphological operator demo should be included in `morphology.rst` file? 
On the other hand, for the edge detector demo, where is it `rst` file?

**Comment by edgarriba** [comment]
that's a good point -- because now we have two levels of documentation:
- API (code reference)
- Applications (e.g https://kornia.readthedocs.io/en/latest/applications/image_augmentations.html)

and I think we are placing the gradio apps everywhere. In my opinion would make more sense to be added to the applications level which is a more high level showcase, later the apis could just reference. The drawback is that we don't have a full coverage yet of all the applications, e.g `Morphological Operators` or `Edge Detection` are missing.

Something discuss with @ducha-aiki some time ago is to compile in the applications all the possible use cases for kornia at a very high level, which basically explains all the roots of computer vision in a wiki collaborative fashion linking to implementation using our api and potentially some integrations (but less priority).

Opinions here ? @ducha-aiki @NimaBoscarino @osanseviero

**Comment by edgarriba** [comment]
@ramon-rd but to be more precise on you question -- morphology.rst and https://kornia.readthedocs.io/en/latest/filters.html#edge-detection

but subkect i guess to change as explained above.

**Comment by ramon-rd** [comment]
Ok @edgarriba  . I'll made the changes in that files and in the future I'll modify it if necessary.

**Comment by NimaBoscarino** [comment]
Personally, I see value in having demos at both levels. I would imagine that the demos at the API level can be very simple, and then the ones at the applications level can be more complex. And since the applications level doesn't yet cover everything, to me that's a compelling reason for making sure that there are demos at the API level.

**Comment by edgarriba** [comment]
perfect -- yeah, possibly for the Demos Sprint v2 we can iterate on that

**Pull request merged**
