### PR TITLE
[Docs] update zca docs

### PR DESCRIPTION
**Pull request by ceroytres**
### Description
Update to the zca whitening docs. Tried to improve clarity and fix some grammar and spelling mistakes. Related to PRs #458  and #566 

### Status
**Ready**

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [x] Docstrings/Documentation updated

### PR Implementer
This is a small checklist for the implementation details of this PR.

If there are any questions regarding code style or other conventions check out our 
[summary](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst).

- [ ] Did you discuss the functionality or any breaking changes before ?
- [x] **Pass all tests**: did you test in local ? `make test`
- [ ] Unittests: did you add tests for your new functionality ?
- [x] Documentations: did you build documentation ? `make build-docs`
- [ ] Implementation: is your code well commented and follow conventions ? `make lint`
- [ ] Docstrings & Typing: has your code documentation and typing ? `make mypy`
- [ ] Update notebooks & documentation if necessary

### KorniaTeam
<details>
  <summary>KorniaTeam workflow</summary>
  
  - [ ] Assign correct label
  - [ ] Assign PR to a reviewer
  - [ ] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if 
        not already in description)

</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>

  - [ ] Do all tests pass? (Unittests, Typing, Linting, Documentation, Environment)
  - [ ] Does the implementation follow `kornia` design conventions?
  - [ ] Is the documentation complete enough ?
  - [ ] Are the tests covering simple and corner cases ?
 
</details>

### CODE REVIEW

**Comment by edgarriba** [comment]
@ceroytres thanks for the contribution. Would be great to see a small colab tutorial showing how this works :)

Besides, what othe operations do you think we are missing here ?
Actually, I was planning after you PR to split `kornia.color` to `kornia.enhance`.

**Comment by ceroytres** [comment]
@edgarriba I'll make colab tutorial for zca. I'll try to get it done in a couple of weeks. I'm starting to get a bit busy again. I'll brainstorm about things that would be neat to see in kornia. Would the roadmap be the place to make suggestions?

**Comment by edgarriba** [comment]
@ceroytres I'll update the roadmap this weekend

**Comment by Kshitij09** [comment]
I'm not able to import `ZCAWhitening` or anything from `kornia.color.zca`. Tried
```python
from kornia.color import ZCAWhitening
from kornia.color.zca import ZCAWhitening
from kornia.color import zca_whiten
```
Isn't it released yet?

cc: @edgarriba 

I'm waiting for colab tutorial @ceroytres :eyes: 

> Besides, what othe operations do you think we are missing here ?

I guess `PCA Whitening` and `PCA Noise` would be on the similar track here. Could be a great addition, especially PCA noise was referred in [Bag of Tricks for Image Classification with Convolutional Neural Networks](https://arxiv.org/abs/1812.01187) paper as part of pre-processing and have shown promising results

**Comment by ceroytres** [comment]
@Kshitij09 I believe you need to install from source in order to use zca right now. I was hoping to make a colab tutorial sometime next week.

**Comment by Kshitij09** [comment]
@ceroytres thanks! I'm looking for effect of applying ZCA whitening on images

**Comment by ceroytres** [comment]
@Kshitij09 I conjured a quick demo on colab. Hopefully it's useful: https://colab.research.google.com/drive/1OhS3MYVGO9ACtKpV5PwpE52ALjO5yzTN?usp=sharing

**Comment by Kshitij09** [comment]
@ceroytres thanks for the tutorial. One question, do we have to fit on whole dataset, or a batch will do as well ?

**Comment by ceroytres** [comment]
Yeah, you can do a batch.

**Comment by edgarriba** [comment]
@ceroytres great tutorial. Free feel to link it to the documentation. We have also https://github.com/kornia/kornia-examples as a pool for tutorials but it needs some reorganization time to be sync with the actual docs.

**Comment by ceroytres** [comment]
@edgarriba do you still want me to contribute the zca example notebook? And would it be to https://github.com/kornia/kornia-examples ?

**Comment by edgarriba** [comment]
@ceroytres that would be great. Are you in slack ? we can discuss details there since we might want the restructure tutorials/examples.

**Comment by ceroytres** [comment]
I’m not on the slack. @edgarriba

**Comment by edgarriba** [comment]
here is the link in case you want to join: https://join.slack.com/t/kornia/shared_invite/zt-csobk21g-CnydWe5fmvkcktIeRFGCEQ

but yeah, a jupyter notebook would be great under `kornia-examples`

**Pull request merged**
