### PR TITLE
chore: ensure onnx for face detector model

### PR DESCRIPTION
**Pull request by johnnv1**
Related to #2559

ensures support to ONNX to the model of the face detector API (YuFaceDetectNet)

### CODE REVIEW

**Comment by cjpurackal** [comment]
did you run the exported model? I'm unsure if it works.

**Comment by johnnv1** [comment]
> did you run the exported model? I'm unsure if it works.

yeap, the raw model looks fine (at least for the tutorial sample)

silly mimicking the tutorial but changing the model to be the onnx 

```py
import numpy as np
import onnxruntime as ort
import torch

ort_session = ort.InferenceSession("t2_YuFace.onnx")

import cv2

import kornia as K

device = torch.device("cpu")  # use 'cuda:0'
dtype = torch.float32
img = K.io.load_image("crowd.jpg", K.io.ImageLoadType.RGB8, device=device)[None, ...].to(dtype=dtype)
img_vis = K.tensor_to_image(img.byte())


class FD(K.contrib.FaceDetector):
    def forward(self, image):
        if self.model is not None:
            del self.model
        img = self.preprocess(image)
        out = self.model_onnx.run(
            None,
            {"images": image.numpy().astype(np.float32)},
        )
        out = {"loc": torch.from_numpy(out[0]), "conf": torch.from_numpy(out[1]), "iou": torch.from_numpy(out[2])}
        return self.postprocess(out, img.shape[-2], img.shape[-1])


model = FD()
model.model_onnx = ort_session

dets = model(img)

from kornia.contrib import FaceDetectorResult

dets = [FaceDetectorResult(o) for o in dets]

# blurring paramters
k: int = 21  # kernel_size
s: float = 35.0  # sigma


def apply_blur_face(img: torch.Tensor, img_vis: np.ndarray, x1, y1, x2, y2):
    # crop the face
    roi = img[..., y1:y2, x1:x2]

    # apply blurring and put back to the visualisation image
    roi = K.filters.gaussian_blur2d(roi, (k, k), (s, s))
    img_vis[y1:y2, x1:x2] = K.tensor_to_image(roi)


for b in dets:
    # draw face bounding box around each detected face
    top_left = b.top_left.int().tolist()
    bottom_right = b.bottom_right.int().tolist()
    scores = b.score.tolist()

    for score, tp, br in zip(scores, top_left, bottom_right):
        x1, y1 = tp
        x2, y2 = br

        if score < 0.7:
            continue  # skip detection with low score
        img_vis = cv2.rectangle(img_vis, (x1, y1), (x2, y2), (0, 255, 0), 2)

        # blur the detected faces
        apply_blur_face(img, img_vis, x1, y1, x2, y2)

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 8))
plt.imshow(img_vis)
plt.axis("off")
plt.show()
```

**Comment by cjpurackal** [comment]
cool :+1:

**Review by edgarriba — APPROVED** [review]
as an idea -- should we also somehow provide the onnx files ? thinking more for the kornia_rs.dnn side

**Comment by johnnv1** [comment]
> as an idea -- should we also somehow provide the onnx files ? thinking more for the kornia_rs.dnn side

I don't think so, but maybe there should be some tutorials on "how to export it" for each device?

**Pull request merged**
