### PR TITLE
[WIP] Parametrize device and dtype fixtures using CLI options

### PR DESCRIPTION
**Pull request by anibali**
### Description
Configure PyTest tests so that they can run for multiple combinations of dtypes/devices in one invocation.

### Status
**Work in progress**

### PR Implementer
This is a small checklist for the implementation details of this PR.

If there are any questions regarding code style or other conventions check out our 
[summary](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst).

- [ ] Did you discuss the functionality or any breaking changes before ?
- [ ] **Pass all tests**: did you test in local ? `make test`
- [ ] Unittests: did you add tests for your new functionality ?
- [ ] Documentations: did you build documentation ? `make build-docs`
- [ ] Implementation: is your code well commented and follow conventions ? `make lint`
- [ ] Docstrings & Typing: has your code documentation and typing ? `make mypy`
- [ ] Update notebooks & documentation if necessary

### KorniaTeam
<details>
  <summary>KorniaTeam workflow</summary>
  
  - [ ] Assign correct label
  - [ ] Assign PR to a reviewer
  - [ ] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if 
        not already in description)

</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>

  - [ ] Do all tests pass? (Unittests, Typing, Linting, Documentation, Environment)
  - [ ] Does the implementation follow `kornia` design conventions?
  - [ ] Is the documentation complete enough ?
  - [ ] Are the tests covering simple and corner cases ?
 
</details>

### CODE REVIEW

**Comment by anibali** [comment]
@edgarriba So far I have only implemented the bare minimum so that you can see the guts of the change.

However, I would like to add further improvements:
* Merge all of test/common.py into conftest.py
  * Remove the imports to dtype and device fixtures in the test case files. This pattern is awkward since it generates a lot of "unused imports" in PyCharm.
  * Add an `all` option for each of the CLI options
* Rename the CLI options since "typetest" is confusing (I'm thinking `--device` and `--dtype` are simple and straightforward)

**Comment by edgarriba** [comment]
@anibali I merged part of your PR in https://github.com/kornia/kornia/pull/560 go ahead with the improvements you mention. Regarding removing imports, wouldn't be a bit unclear for readability to get from where device and dtype come from ?

**Comment by anibali** [comment]
I understand where you're coming from regarding the imports, but it's fairly conventional to define shared fixtures in `conftest.py` when using PyTest (https://docs.pytest.org/en/latest/fixture.html#conftest-py-sharing-fixture-functions). So I think that most developers would not be surprised to find fixtures defined in `conftest.py`. Since the link between the import and the test parameters is not super strong in the current setup anyway (eg IDEs detect them as unused imports since they are not directly referenced), I don't think much would be lost in terms of readability and in fact it would make managing imports easier. Of course this is somewhat subjective though.

**Comment by edgarriba** [comment]
sure, then let's do it. Learning pytest on the fly :)
when do you think it can be done or how much time it will take?

I'm doing a release within the next hours since we introduced minor patches like exposing align_corners which seems quite critical depending on what you want to do with your geometric transforms. We can inlcude this fixtures refactor for the next minor release since I'll be also working on the gpu automated tests integration with drone.io ans aws.

I also introduced more tools for documentations checking and stuff. BTW, what do you think about introducing autoformat by defaults like black ?

**Comment by anibali** [comment]
I'm about to go to sleep, so I definitely won't be able to do anything for the release that you are about to make. However, I don't think that it will take too much time to do---I can have more of a look tomorrow to get a better idea.

Good to hear that you are adding explicit options for align_corners and automated GPU tests!

RE: Black, I've not had any experience with it personally. My immediate reaction is that there are always exceptions to rules (and code formatting rules are no exception)! As a general observation it seems like making contributions here is becoming more and more... intimidating, I guess, with lots of rules to follow. I do understand that you want to have good guidelines and maintain consistency. But I believe that allowing contributors to have some level of agency is important for engagement. And at least for me personally, I'd probably be too scared to make a PR if I was just starting now. On the other hand, I don't need to deal with all of your code reviewing workload, so it's easy for me to say 😉

**Comment by edgarriba** [comment]
sure, no rush. Minor releases are just checkpoints of the library. Such things like Black (or any automated formatting tool) is to release user about the code format. We have to find the balance between adding minimal implementations so that later others can improve (like supporting more data types/devices). But at the same time since the project is growing and we have to have to be control over different aspects so future changes don't affect to the existing behavior.

**Comment by anibali** [comment]
I understand, it's definitely important to ensure the quality of the project remains high as it expands. Personally I think that enforcing the use of an auto formatter might be a bridge too far, but of course that's your call. Just giving my 2 cents since you asked :smile:

**Pull request closed without merging**
