### PR TITLE
Better lightglue for DoG features

### PR DESCRIPTION
**Pull request by ducha-aiki**
#### Changes

Fixes # (issue)

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Review by johnnv1 — CHANGES_REQUESTED** [review]
It needs to be rebased based on the main. The last commit 04f223a37add50b58f52535f1c5dab8609b3e5d3 looks good

**Comment by edgarriba** [comment]
@ducha-aiki the easiest is to checkout main and cherry-pick that commit

**Comment by ducha-aiki** [comment]
I will create new PR then

**Comment by ducha-aiki** [comment]
> @ducha-aiki the easiest is to checkout main and cherry-pick that commit
I am always just create new clone and manually move files, not this git voodoo :)

**Pull request closed without merging**
