### PR TITLE
remove numpy dependency

### PR DESCRIPTION
**Pull request by lferraz**
### Description
A few sentences describing the changes proposed in this pull request.

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [ ] Docstrings/Documentation updated

### PR Implementer
This is a small checklist for the implementation details of this PR.

If there are any questions regarding code style or other conventions check out our
[summary](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst).

- [ ] Did you discuss the functionality or any breaking changes before ?
- [ ] **Pass all tests**: did you test in local ? `make test`
- [ ] Unittests: did you add tests for your new functionality ?
- [ ] Documentations: did you build documentation ? `make build-docs`
- [ ] Implementation: is your code well commented and follow conventions ? `make lint`
- [ ] Docstrings & Typing: has your code documentation and typing ? `make mypy`
- [ ] Update notebooks & documentation if necessary

### KorniaTeam
<details>
  <summary>KorniaTeam workflow</summary>

  - [ ] Assign correct label
  - [ ] Assign PR to a reviewer
  - [ ] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if
        not already in description)

</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>

  - [ ] Do all tests pass? (Unittests, Typing, Linting, Documentation, Environment)
  - [ ] Does the implementation follow `kornia` design conventions?
  - [ ] Is the documentation complete enough ?
  - [ ] Are the tests covering simple and corner cases ?

</details>

### CODE REVIEW

**Review by edgarriba — APPROVED** [review]

**Comment by edgarriba** [comment]
@pmeier apparently this is needed for python 3.9

**Comment by pmeier** [comment]
@lferraz @edgarriba what exactly are you doing that `numpy` is not optional?

**Comment by lferraz** [comment]
hi @pmeier 

> @lferraz @edgarriba what exactly are you doing that numpy is not optional?

I think it is only because typing...
This PR is only to remove the limitation about the numpy version that was `numpy<=1.19`.

Probably we could follow the same strategy as pytorch in version 1.9 removing numpy.

**Comment by pmeier** [comment]
> Probably we could follow the same strategy as pytorch in version 1.9 removing numpy.

Yes. If `numpy` is only needed for typing, only install it as a development dependency.

**Comment by lferraz** [comment]
@edgarriba, are we using `numpy` only for typing or for something else? In that case the @pmeier proposal makes a lot of sense.

**Comment by edgarriba** [comment]
Yeap - only for typing

**Comment by lferraz** [comment]
hi @pmeier 

I have checked the code and I am not sure how to remove `numpy`. What's the best approach to do it? The only way I found is using a `try` `except` around the import.

```
try:
  import numpy as np
except:
  pass
```

Do you know a cleaner way? I tried to see how it was done in pytorch but I couldn't find the exact commit.

**Comment by pmeier** [comment]
@lferraz 

The usual way is to simply quote the annotation, i.e. `def foo() -> "np.ndarray"`. That way it doesn't have to be available at runtime, but can still be analyzed if available when type checking.

I had a quick look through the repo and I found this:

https://github.com/kornia/kornia/blob/25cb90b1775fa2244790cd8f46c6120f68106c6e/kornia/utils/image.py#L21-L22

Thus, `kornia` or at least part of it depends on `numpy` and it should be list as requirement.

**Comment by edgarriba** [comment]
> @lferraz
> 
> The usual way is to simply quote the annotation, i.e. `def foo() -> "np.ndarray"`. That way it doesn't have to be available at runtime, but can still be analyzed if available when type checking.
> 
> I had a quick look through the repo and I found this:
> 
> https://github.com/kornia/kornia/blob/25cb90b1775fa2244790cd8f46c6120f68106c6e/kornia/utils/image.py#L21-L22
> 
> Thus, `kornia` or at least part of it depends on `numpy` and it should be list as requirement.

I think this could be hacked around since the dependency is very weak in the algorithms implementation

**Comment by lferraz** [comment]
> > @lferraz
> > The usual way is to simply quote the annotation, i.e. `def foo() -> "np.ndarray"`. That way it doesn't have to be available at runtime, but can still be analyzed if available when type checking.
> > I had a quick look through the repo and I found this:
> > https://github.com/kornia/kornia/blob/25cb90b1775fa2244790cd8f46c6120f68106c6e/kornia/utils/image.py#L21-L22
> > 
> > Thus, `kornia` or at least part of it depends on `numpy` and it should be list as requirement.
> 
> I think this could be hacked around since the dependency is very weak in the algorithms implementation

Agree we can directly remove this check. 
The exception should be raised here:
https://github.com/kornia/kornia/blob/25cb90b1775fa2244790cd8f46c6120f68106c6e/kornia/utils/image.py#L28

**Comment by edgarriba** [comment]
> > > @lferraz
> > > The usual way is to simply quote the annotation, i.e. `def foo() -> "np.ndarray"`. That way it doesn't have to be available at runtime, but can still be analyzed if available when type checking.
> > > I had a quick look through the repo and I found this:
> > > https://github.com/kornia/kornia/blob/25cb90b1775fa2244790cd8f46c6120f68106c6e/kornia/utils/image.py#L21-L22
> > > 
> > > Thus, `kornia` or at least part of it depends on `numpy` and it should be list as requirement.
> > 
> > 
> > I think this could be hacked around since the dependency is very weak in the algorithms implementation
> 
> thank you so much for this tip @pmeier , I didn't know that trick with mypy.
> 
> Agree we can directly remove this check.
> The exception should be raised here:
> 
> https://github.com/kornia/kornia/blob/25cb90b1775fa2244790cd8f46c6120f68106c6e/kornia/utils/image.py#L28

great - then go ahead with this

**Comment by lferraz** [comment]
> great - then go ahead with this

`mypy` complaints... :(. Look at the tests... :(

**Comment by pmeier** [comment]
@lferraz 

Insert this at the top of the file:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import numpy as np
```

**Review by edgarriba — APPROVED** [review]

**Pull request merged**
