### PR TITLE
making `compute_correspond_epilines` work with fundamental and point of volumetric tensors

### PR DESCRIPTION
**Pull request by nitaifingerhut**
#### Changes

Fixes # (issue)

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by nitaifingerhut** [comment]
@shijianjian just a small fix to allow computing corresponding epilines for (B, T, 3, 3) fundamental with (B, T, N, 2/3) points.

**Review by edgarriba — APPROVED** [review]
@nitaifingerhut thanks for the PR -- it LGTM. Looking at the test you added, might be worth to invest a bit of time to adapt `compute_correspond_epilines` as well ? Can be done in a next PR though.

**Comment by nitaifingerhut** [comment]
@edgarriba what exactly do you think need to be adapted? The method now fully support volumetric data

**Comment by nitaifingerhut** [comment]
also, this test: `DeepSource: Python` fails due to reason unrelated to this PR. how would you like to proceed with that?

**Pull request merged**
