### PR TITLE
Quaternion pow bug fix (div by zero)

### PR DESCRIPTION
**Pull request by cjpurackal**
#### Changes

Divide by zero error in case of zero vector inside pow. Can causes issues in dependent functions like slerp.

#### Type of change

- [x] 🧪 Tests Cases
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by ducha-aiki — APPROVED** [review]

**Review by edgarriba — APPROVED** [review]
LGTM. For the tests, seems  that your branch is outdated

**Comment by cjpurackal** [comment]
> LGTM. For the tests, seems that your branch is outdated

really? I did sync it with kornia/kornia:master and seems like its up-to-date..

**Comment by ducha-aiki** [comment]
@edgarriba it is weird - sometimes, GH does not start testing, when CI is overloaded...and then never starts when there is a capacity - then one needs one more commit to push it again. I have experienced that last couple of weeks.

**Comment by ducha-aiki** [comment]
Oh, crap. That happened again, after the pre-commit bot commit :(

**Pull request merged**
