### PR TITLE
fix issue of image_histogram2d

### PR DESCRIPTION
**Pull request by lyhyl**
#### Changes

Fixes # (issue)
https://github.com/kornia/kornia/issues/1294

#### Type of change

- [ ] 📚  Documentation Update
- [x] 🧪 Tests Cases
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by lyhyl** [comment]
I just add a parameter for `test_uniform_hist` and `test_uniform_dist` to test BxCxHxW and CxHxW input.
DeepSource Analysis said I should mark these functions as static method, but the other functions are not.
What standard should I compliant with? The original or DeepSource Analysis?

**Review by lyhyl — COMMENTED** [review]
reviewed

**Review by edgarriba — APPROVED** [review]
LGTM

**Comment by edgarriba** [comment]
@lyhyl no problem for deepsource for now - we need the disable that error since possibly doesn't make sense for us in testing.

Besides, I think it's to add a numerical test to double check also this https://github.com/kornia/kornia/issues/1217

**Pull request merged**
