### PR TITLE
Fixes issue-452

### PR DESCRIPTION
**Pull request by elijose55**
Fixed the import mentioned in the issue.

### CODE REVIEW

**Comment by edgarriba** [comment]
@elijose55 what's the actual change ?

**Comment by elijose55** [comment]
I changed

**Comment by elijose55** [comment]
in kornia/examples/homography_regression/homography.ipynb changed the import:
import torchgeometry as tgm

to:
import kornia as tgm

**Comment by edgarriba** [comment]
Ok, I see. Will double check the examples since probably for testing purposes we might to export to a .py file

**Pull request merged**
