### PR TITLE
fix bugs shift_rgb

### LINKED ISSUE #1859: Bugs when using RandomRGBShift
### Describe the bug

When running RandomRGBShift augmentation on gpus I came across this error 

```
  File "/usr/local/lib/python3.8/dist-packages/kornia/augmentation/_2d/intensity/random_rgb_shift.py", line 100, in apply_transform
    return shift_rgb(inp, params['r_shift'], params['g_shift'], params['b_shift'])
  File "/usr/local/lib/python3.8/dist-packages/kornia/enhance/shift_rgb.py", line 17, in shift_rgb
    shifted = (image + torch.Tensor(shifts).view(1, 3, 1, 1).to(image)).clamp_(min=0, max=1)
ValueError: only one element tensors can be converted to Python scalars
```
after checking the code I think the problem is that 
```
shifts = [params['r_shift'], params['g_shift'], params['b_shift']]
shifted = (image + torch.Tensor(shifts).view(1, 3, 1, 1).to(image)).clamp_(min=0, max=1)
```
and also I am not sure about `.view(1,3,1,1)` shouldn't it be `.view(-1,3,1,1)`

### Reproduction steps

```bash
1. setting up RandomRGBShift augmentation
2. Using RandomRGBShift augmentation with gpus and batchsize > 1
```

### Expected behavior

```
  File "/usr/local/lib/python3.8/dist-packages/kornia/augmentation/_2d/intensity/random_rgb_shift.py", line 100, in apply_transform
    return shift_rgb(inp, params['r_shift'], params['g_shift'], params['b_shift'])
  File "/usr/local/lib/python3.8/dist-packages/kornia/enhance/shift_rgb.py", line 17, in shift_rgb
    shifted = (image + torch.Tensor(shifts).view(1, 3, 1, 1).to(image)).clamp_(min=0, max=1)
ValueError: only one element tensors can be converted to Python scalars
```

### Environment

```shell
- PyTorch Version : 1.10
- Linux
- How you installed PyTorch (`pip`):
- Python version: 3.8
- cuda:11.3.0-cudnn8
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by duc12111**
#### Changes

Fixes   #1859

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Review by edgarriba — APPROVED** [review]
LGTM

**Review by edgarriba — COMMENTED** [review]
@duc12111 is there any quick tests we can add here to verify ?

**Comment by duc12111** [comment]
https://github.com/kornia/kornia/pull/1706. I think the test for the given error is already implemented here. I can add one more test for the batch > 1 cases

**Comment by duc12111** [comment]
@edgarriba I have added new tests for batch > 1. I also copied the tests from https://github.com/kornia/kornia/pull/1706.

**Pull request merged**
