### PR TITLE
add weighted PnP

### PR DESCRIPTION
**Pull request by ducha-aiki**
It works for noise, but doesn't really work against outliers.

#### Changes

Fixes # (issue)

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Review by edgarriba — APPROVED** [review]
LGTM

**Review by johnnv1 — APPROVED** [review]

**Comment by edgarriba** [comment]
@ducha-aiki any idea why the tests are failing?

**Comment by edgarriba** [comment]
@ducha-aiki can you double check why is this crashing and merge ?

**Comment by ducha-aiki** [comment]
@edgarriba Well, because method of applying weights is not bullet-proof in principle. I have another idea, but haven't worked it out yet

**Comment by edgarriba** [comment]
can we add just a numerical test with fixed seed to make sure reproducibility?

**Comment by ducha-aiki** [comment]
@edgarriba actually I was repeating weights among wrong dim. Now fixed and works well.

**Pull request merged**
