### PR TITLE
Add Dense SIFT

### PR DESCRIPTION
**Pull request by ducha-aiki**
### Description
A few sentences describing the changes proposed in this pull request.
Adds DenseSIFT (baseline: vlfeat https://www.vlfeat.org/overview/dsift.html) 
Addresses https://github.com/kornia/kornia/issues/462 and https://github.com/kornia/kornia/issues/459

Things, which are now missing:

- [ ] proper padding to allow having output resolution == input resolution
- [ ] tests
- [ ] benchmark versus some baseline, e.g. vlfeat
- [ ] documentation of the design choices.

image

### Status
**Work in progress**

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [ ] Docstrings/Documentation updated

### PR Implementer
This is a small checklist for the implementation details of this PR.

If there are any questions regarding code style or other conventions check out our 
[summary](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst).

- [ ] Did you discuss the functionality or any breaking changes before ?
- [ ] **Pass all tests**: did you test in local ? `make test`
- [ ] Unittests: did you add tests for your new functionality ?
- [ ] Documentations: did you build documentation ? `make build-docs`
- [ ] Implementation: is your code well commented and follow conventions ? `make lint`
- [ ] Docstrings & Typing: has your code documentation and typing ? `make mypy`
- [ ] Update notebooks & documentation if necessary

### KorniaTeam
<details>
  <summary>KorniaTeam workflow</summary>
  
  - [ ] Assign correct label
  - [ ] Assign PR to a reviewer
  - [ ] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if 
        not already in description)

</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>

  - [ ] Do all tests pass? (Unittests, Typing, Linting, Documentation, Environment)
  - [ ] Does the implementation follow `kornia` design conventions?
  - [ ] Is the documentation complete enough ?
  - [ ] Are the tests covering simple and corner cases ?
 
</details>

### CODE REVIEW

**Comment by ducha-aiki** [comment]
@connorlee77 hi,

In case of you have some time - I would appreciate if you help finish this PR, specifically - by checking how the padding/output shape is handled in vlfeat, so we can port it here.

**Comment by connorlee77** [comment]
Oh yeah I'm a little busy these weeks, but I'll try to get to it when I can!

**Review by edgarriba — APPROVED** [review]
LGTM. Future thing would be to externalize HoG as requested @twsl

**Comment by edgarriba** [comment]
@ducha-aiki have you tried by any chance to torchscript ?

**Comment by ducha-aiki** [comment]
No, but the DenseSIFT should be jittable

**Comment by edgarriba** [comment]
that will a strong feature I believe, specially the c++ interface of that. Will play with it

**Pull request merged**
