### PR TITLE
I added html file for module Line Fitting

### PR DESCRIPTION
**Pull request by kadirnar**
#### Changes
- [X] I added line-fitting.html file.

Fixed https://github.com/kornia/kornia/issues/53#issue-401715507

#### Type of change

- [X] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by kadirnar** [comment]
Hi @edgarriba ,

I couldn't find the .rst file for module Line Fitting.
Demo App: https://huggingface.co/spaces/kornia/Line-Fitting

**Comment by NimaBoscarino** [comment]
@p-mishra1 The docs for `fit_line` on the website are here: https://kornia.readthedocs.io/en/latest/geometry.line.html#kornia.geometry.line.fit_line

The .rst file is here: https://github.com/kornia/kornia/blob/master/docs/source/geometry.line.rst

**Comment by kadirnar** [comment]
Added gradio file path to x file

> @p-mishra1 The docs for `fit_line` on the website are here: https://kornia.readthedocs.io/en/latest/geometry.line.html#kornia.geometry.line.fit_line
> 
> The .rst file is here: https://github.com/kornia/kornia/blob/master/docs/source/geometry.line.rst

Thank you so much. What should I do for the tutorial repo?

**Review by edgarriba — APPROVED** [review]
@kadirnar for the tutorials repo adding badge will be enough. I might have some confusion in naming in the demo app but i'll post in HF directly.

If you are interested in this topic, I had pending to provide a tutorial for 3d line fitting -- in theory no changes are required in the api, just need to try.

**Comment by kadirnar** [comment]
> @kadirnar for the tutorials repo adding badge will be enough. I might have some confusion in naming in the demo app but i'll post in HF directly.
> 
> If you are interested in this topic, I had pending to provide a tutorial for 3d line fitting -- in theory no changes are required in the api, just need to try.

There is no colab file for this module. Which file should I add badge to?
Demo App: https://huggingface.co/spaces/kornia/Line-Fitting

**Comment by edgarriba** [comment]
oh right, only python example. Feel free to create one if you want

**Pull request merged**
