### PR TITLE
setup.py: Declare support for Python 3.6+

### PR DESCRIPTION
**Pull request by cclauss**
#### Changes

Fixes # (issue)

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by edgarriba** [comment]
@cclauss should we keep this even if we don't test on 3.7 / 3.9 ?

**Comment by cclauss** [comment]
Yes.  If we test successfully on 3.6, 3.8, and 3.10 then there is a small chance that we would fail on 3.7 or 3.9.  We want to test without burning down the planet.

**Comment by edgarriba** [comment]
for some reason pytorch do not have stable support yet to python 3.10 -- let hold this one

**Comment by johnnv1** [comment]
Done at #2025

**Pull request closed without merging**
