### PR TITLE
Fix PLR0124

### PR DESCRIPTION
**Pull request by ashnair1**
#### Changes

Pre-commit has been failing because ruff was raising error [PLR0124](https://beta.ruff.rs/docs/rules/comparison-with-itself/) in this file. 

Alternatively we could just add `--ignore PLR0124` as an arg to ruff in `.pre-commit-config.yaml`.

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by edgarriba** [comment]
where do you see this error ? the pre-commit job seems to pass in this PR

**Comment by ashnair1** [comment]
This error is present in all other PRs and even the latest commit on master. It's not present here because of the change included.

**Comment by edgarriba** [comment]
gotcha -- lets add in https://github.com/kornia/kornia/pull/2422/files#diff-33ac87ef641c4bbe578422c5a6f700d3c8c38651fc82176c444dbde2b5700120L68

```python
        x1 = TensorWrapper(data)
        x2 = TensorWrapper(data)

        self.assert_close(x1.ge(x2), x1 >= x2)
```

**Comment by ashnair1** [comment]
Like this?

**Review by edgarriba — APPROVED** [review]

**Pull request merged**
