### PR TITLE
[enhance] improve flipping and cropping speed

### PR DESCRIPTION
**Pull request by shijianjian**
#2175 and #2136

RandomCrop:
```
Baseline from #2175
[5.921756925, 6.9425626739999995, 6.568994523999999, 7.860189029000001, 7.356724565]
Before:
[26.677106356, 26.578449804, 27.665404369, 26.978094082, 26.892204961000004]
After:
[4.842821216000004, 5.157504515999996, 5.479773302000005, 5.157385547000004, 4.902601369999999]
```

Hflip, VFlip:
```
Before:
1.8668735620000003
After:
0.4162677849999996
```

### CODE REVIEW

**Comment by edgarriba** [comment]
can you report before / after timings ?

**Review by edgarriba — APPROVED** [review]
LGTM. Lets add timings in the Pr message so that can be tracked

**Comment by shijianjian** [comment]
Any ideas how to update the pre-commit?

It looks like it will report as failure after running black, while it should be a pass.
``` 
files were modified by this hook
```

**Comment by edgarriba** [comment]
> it will report as failure after running black, while it sho

this will be fixed here: https://github.com/kornia/kornia/pull/2176

**Pull request merged**
