### PR TITLE
Feat/randombrightness contrast saturation hue

### LINKED ISSUE #1836: Refactoring `ColorJitter` and `ColorJiggle` into smaller components
## 🚀 Feature
`ColorJitter` and `ColorJiggle` currently are too packed. It is better to develop smaller components and rewrite these as compositions of smaller components.

## Motivation

Smaller components can be applied individually. For e.g., brightness and contrast jitterings are applicable to gray images, but currently they are under `ColorJitter` and `ColorJiggle` which are not applicable to gray images.

## Pitch

```
class BrightnessJitter(...):
    ...


class ContrastJitter(...):
    ...


class HueJitter(...):
    ...


class ColorJitter(nn.Sequential):
    def __init__(...):
        self.brightness_jitter = BrightnessJitter(...)
        self.contrast_jitter  = ContrastJitter(...)
        self.hue_jitter = HueJitter(...)
        ...

```

### PR DESCRIPTION
**Pull request by duc12111**
#### Changes
Add RandomBrightness/Contrast/Saturation/Hue and tests

Fixes #1836

#### Type of change

- [x] 📚  Documentation Update
- [x] 🧪 Tests Cases
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by duc12111** [comment]
Some pictures to add to documentation
RandomContrast
RandomContrast
RandomHue
RandomHue
RandomSaturation
RandomSaturation
RandomBrightness
RandomBrightness

**Review by edgarriba — APPROVED** [review]
Amazing work! For completeness can you implement the skipped tests here or in a follow up pr

**Comment by duc12111** [comment]
Hi @edgarriba,
I can add some tests in the follow-up pr and also fix the bugs mentioned here https://github.com/kornia/kornia/issues/1836#issuecomment-1287481932

**Comment by edgarriba** [comment]
@ducha-aiki @shijianjian please, review and merge

**Review by ducha-aiki — APPROVED** [review]

**Pull request merged**
