### PR TITLE
Fix Boxes.from_tensor(boxes, mode="vertices")

### LINKED ISSUE #1738: mode="vertices" in Boxes.from_tensor add +1 to boxes width and height
### Describe the bug

mode="vertices" in Boxes.from_tensor add +1 to boxes width and height

### Reproduction steps

```python
from kornia.geometry.boxes import Boxes

boxes = torch.tensor([[[355,10, 660,250], [10,125, 200,400]]]) 
vertices = Boxes.from_tensor(boxes).to_tensor('vertices')
assert (vertices == Boxes.from_tensor(vertices, mode="vertices").to_tensor("vertices")) # <-- fails
```
original vertices
```
tensor([[[[355.,  10.],
          [660.,  10.],
          [660., 250.],
          [355., 250.]],

         [[ 10., 125.],
          [200., 125.],
          [200., 400.],
          [ 10., 400.]]]])


```
after from and to boxes
```
tensor([[[[355.,  10.],
          [661.,  10.],
          [661., 251.],
          [355., 251.]],

         [[ 10., 125.],
          [201., 125.],
          [201., 401.],
          [ 10., 401.]]]])

```

### Expected behavior

To return the same original boxes

### Environment

```shell
kornia 0.6.5
torch 1.9.1+cpu
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hal-314**
#### Changes

Fixes #1738

#### Type of change

- [ ] 📚  Documentation Update
- [ ] 🧪 Tests Cases
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔬 New feature (non-breaking change which adds functionality)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 This change requires a documentation update

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Did you update CHANGELOG in case of a major change?

### CODE REVIEW

**Comment by hal-314** [comment]
Failing CI seems to be due to mypy failing in a code region that I didn't touch it in this PR. I don't understand why this PR is failing and the other two (#1739 & #1741) that I made almost simultaneously didn't.


```bash

=================================== FAILURES ===================================
_________________________________ test session _________________________________
mypy exited with status 1.
=============================== warnings summary ===============================
....

===================================== mypy =====================================
kornia/augmentation/container/image.py:347: error: Invalid index type
"Union[str, Any]" for "List[ParamItem]"; expected type "SupportsIndex"  [index]
                    param = params[name] if name in params else param
                                   ^
kornia/augmentation/container/image.py:356: error: Item "None" of
"Union[ParamItem, Any, None]" has no attribute "data"  [union-attr]
                    input = module.inverse(input, param.data, extra_args=e...
                                                  ^
kornia/augmentation/container/image.py:356: error: Argument 2 to "inverse" of
"ImageSequential" has incompatible type
"Union[Dict[Any, Any], List[Any], None, Any]"; expected
"Optional[List[ParamItem]]"  [arg-type]
                    input = module.inverse(input, param.data, extra_args=e...
                                                  ^
kornia/augmentation/container/augment.py:247: error: Invalid index type
"Union[str, Any]" for "List[ParamItem]"; expected type "SupportsIndex"  [index]
                        param = params[name] if name in params else param
                                       ^
Found 4 errors in 2 files (checked 127 source files)
=========================== short test summary info ============================
FAILED test/__init__.py::mypy-status
= 1 failed, 15531 passed, 220 skipped, 41 xfailed, 20 xpassed, 997 warnings in 1016.60s (0:16:56) =
```

**Comment by edgarriba** [comment]
@hal-314 don't worry about this, is a mypy issue. I'll try to fix over the weekend. It's blocking other PRS too

**Review by shijianjian — COMMENTED** [review]
Hi @hal-314, I am wondering if you can add more docs in this PR for this feature.

Essentially, shouldn't it perform the "minus one" when "vertices_plus" to restore the numerics? I am a little bit lost in the logic here.

**Review by shijianjian — APPROVED** [review]

**Review by edgarriba — APPROVED** [review]
LGTM. I suggest to add numerical tests later lik the example you provided

**Pull request merged**
