### PR TITLE
Prototype vmap

### PR DESCRIPTION
**Pull request by justanhduc**
I have been playing with `vmap` for a bit and while it has a lot of potential, I am not sure if it is suitable here. Here are some of my thoughts

- Functions wrapped by `vmap` do not recognize keyword arguments.
- It does not handle multiple leading batch dimensions natively. One workaround is to call `vmap` recursively for each batch dimension.
- Regarding usage, it cannot handle inputs without batch dimension. For that case, we still have to use `view`.
- `vmap` is designed to parallelize function without parallelization ability. In our case, we can already parallelize it by reshaping the images. In that sense, using `vmap` seems a bit overkill.

Finally, if we want to use it, seems like we need to wait at least two more releases of Pytorch. The version I used to test `vmap` is `'1.11.0.dev20211005'`.

### CODE REVIEW

**Comment by justanhduc** [comment]
@t-vi Yeah it is a bit limited at the moment. Especially the biggest drawback is not supporting keyword arguments, so it is not possible to have it in wrapper and pass kwargs.

**Comment by t-vi** [comment]
@justanhduc  You say it. But so I don't have any insights into the PyTorch plans there, but "keyword arguments not supported" has been the state for autograd functions long enough for me to not hold my breath until they are supported in vmap.
So if you wanted to use vmap in a very generic way, you would likely need have a decidedly clever introspecting wrapper...

**Comment by edgarriba** [comment]
@t-vi @pmeier yeap, seems that vmap seems more suitable for low level control. However, we still have this issue about auto-batching + torchscript :)

**Comment by zou3519** [comment]
Hi @justanhduc , the vmap in the PyTorch nightly binaries is an older version of the vmap prototype that we're planning on replacing with the newer vmap implementation from functorch (https://github.com/facebookresearch/functorch).

It has many improvements over the vmap in the PyTorch nightly binaries:
- It supports kwargs!
- It is faster

>  - It does not handle multiple leading batch dimensions natively. One workaround is to call vmap recursively for each batch dimension.
> - Regarding usage, it cannot handle inputs without batch dimension. For that case, we still have to use view.

These are all good points. 

> - vmap is designed to parallelize function without parallelization ability. In our case, we can already parallelize it by reshaping the images. In that sense, using vmap seems a bit overkill.

For your use case, it sounds like `vmap` is more of a convenience thing. Sometimes it's difficult to figure out how to batch an expression; for those use cases, `vmap` is helpful. 

> Finally, if we want to use it, seems like we need to wait at least two more releases of Pytorch. The version I used to test vmap is '1.11.0.dev20211005'.

Although vmap isn't beta or stable yet, many people have started using it. We're currently on a sprint to harden the prototype so that it can be more widely used. If you're interested in maintaining a branch that uses vmap we'd be happy to chat more and help.

**Comment by justanhduc** [comment]
@zou3519 wonderful! I have a quick question. Can `vmap` be jitted or will it be in the future? It would be the most helpful to us as our current way of auto batching cannot be jitted.

**Comment by zou3519** [comment]
>  is there any timeframe to get a stable pytorch version with functorch/vmap ? In the meantime, do you have any suggestion for our current use case excluding ?

Right now we're looking at a release alongside PyTorch 1.11. So that's roughly early next year. 

Could you tell me a bit more about your use case please (or let me know if there's someplace I could read about it)? (I jumped in here in the middle of discussion)

> I have a quick question. Can vmap be jitted or will it be in the future? It would be the most helpful to us as our current way of auto batching cannot be jitted.

vmap can't be jitted right now, but that's something we're looking into for the future :). What are your use cases for jitting? Performance improvements?

**Comment by justanhduc** [comment]
@zou3519 regarding the use cases of `vmap`, currently most functions and modules support only 4D image shape and 5D video shape. We would like to make Kornia a more general CV GPU library so we want to support 2D, 3D and even multiple batch images as well. We are doing this by simply `view`ing the input tensor, applying the function and re-`view`ing again in a decorator. This solution is not very nice as it needs to pass `args` and `kwargs`, which cannot be jitted for now. `vmap` may provide a more native solution and when `vmap` can be jitted, it will fix the problem of the current solution. And moreover, I think it is also possible to restructure functions to work natively with 2D and 3D images and use `vmap` to make it deep learning style. Do you have anything to add/comment @edgarriba?

**Comment by edgarriba** [comment]
> @zou3519 regarding the use cases of `vmap`, currently most functions and modules support only 4D image shape and 5D video shape. We would like to make Kornia a more general CV GPU library so we want to support 2D, 3D and even multiple batch images as well. We are doing this by simply `view`ing the input tensor, applying the function and re-`view`ing again in a decorator. This solution is not very nice as it needs to pass `args` and `kwargs`, which cannot be jitted for now. `vmap` may provide a more native solution and when `vmap` can be jitted, it will fix the problem of the current solution. And moreover, I think it is also possible to restructure functions to work natively with 2D and 3D images and use `vmap` to make it deep learning style. Do you have anything to add/comment @edgarriba?

@justanhduc You described very precisely :)

**Pull request closed without merging**
