### PR TITLE
Initiated changelog CI.

### PR DESCRIPTION
**Pull request by shijianjian**
### Description

Auto-generate the changelog by using PR title and labels.

For doing so, create a PR with a title of **Release 9.9.9 (10-29-2020)** or so. Then it will auto-generate the title.

Label will be mapped to the corresponding area by:
```
    "group_config": [
      {
        "title": "Bug Fixes",
        "labels": ["bug", "bugfix"]
      },
      {
        "title": "Code Improvements",
        "labels": ["improvements", "enhancement"]
      },
      {
        "title": "New Features",
        "labels": ["feature", "feature request"]
      },
      {
        "title": "Documentation Updates",
        "labels": ["docs", "documentation", "doc"]
      }
    ]
```

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [ ] New tests added to cover the changes
- [ ] Docstrings/Documentation updated

### PR Implementer
This is a small checklist for the implementation details of this PR.

If there are any questions regarding code style or other conventions check out our 
[summary](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst).

- [ ] Did you discuss the functionality or any breaking changes before ?
- [ ] **Pass all tests**: did you test in local ? `make test`
- [ ] Unittests: did you add tests for your new functionality ?
- [ ] Documentations: did you build documentation ? `make build-docs`
- [ ] Implementation: is your code well commented and follow conventions ? `make lint`
- [ ] Docstrings & Typing: has your code documentation and typing ? `make mypy`
- [ ] Update notebooks & documentation if necessary

### KorniaTeam
<details>
  <summary>KorniaTeam workflow</summary>
  
  - [ ] Assign correct label
  - [ ] Assign PR to a reviewer
  - [ ] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if 
        not already in description)

</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>

  - [ ] Do all tests pass? (Unittests, Typing, Linting, Documentation, Environment)
  - [ ] Does the implementation follow `kornia` design conventions?
  - [ ] Is the documentation complete enough ?
  - [ ] Are the tests covering simple and corner cases ?
 
</details>

### CODE REVIEW

**Review by edgarriba — APPROVED** [review]

**Comment by edgarriba** [comment]
@shijianjian then as a maintainers do we have to take care that every PR before merging has the proper label, rigth ? any automated tool for this ?

**Review by ducha-aiki — APPROVED** [review]

**Comment by shijianjian** [comment]
@edgarriba In theory, yes. We need to give a good title and label for all the PRs. It cannot be automated since the tool can not be that smart to detect the code to see if it a bug fix or doc fix.

The label can be edited after the merge as well. Only need to ensure before running this script.

**Comment by edgarriba** [comment]
@shijianjian can you check this ? https://github.com/kornia/kornia/actions/runs/371207225
seems to not be working

**Comment by shijianjian** [comment]
It is alright. It failed to detect the title format of **Release 9.9.9 (10-29-2020)**. It will auto-gen if the title is properly formated.

**Pull request merged**
